import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'vi' | 'ja';

interface SimpleLanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const SimpleLanguageContext = createContext<SimpleLanguageContextType | undefined>(undefined);

// Simple translations for Home page only
const translations = {
  en: {
    'home.hero.badge': 'Precision Agriculture Technology',
    'home.hero.title1': 'Precise signals.',
    'home.hero.title2': 'Smarter sensing.',
    'home.hero.title3': 'Sustainable growth.',
    'home.hero.subtitle': 'Transform your farm with intelligent, end-to-end agricultural technology solutions. Optimize every decision from soil to harvest.',
    'home.hero.explore': 'Explore Solutions',
    'home.hero.demo': 'Request Demo',
    
    'home.vision.title': 'Our Vision',
    'home.vision.subtitle': 'To become the world\'s leading provider of intelligent, end-to-end agricultural technology solutions for perennial plant farms — enabling them to thrive economically, ecologically, and socially.',
    'home.mission.title': 'Our Mission',
    'home.mission.text1': 'We empower farmers and agricultural businesses through a unified ecosystem of hardware and software — including autonomous drones, robotics, IoT sensors, and AI-powered analytics — to optimize every decision from soil to harvest.',
    'home.mission.text2': 'Our mission is to transform agriculture through precision, automation, and insight, delivering measurable impact to both people and planet.',
    'home.stats.farms': 'Farms Optimized',
    'home.stats.data': 'Data Points Daily',
    'home.stats.yield': 'Yield Increase',
    'home.stats.water': 'Water Saved',
    
    'home.solutions.title': 'Intelligent Solutions',
    'home.solutions.subtitle': 'A complete ecosystem of cutting-edge agricultural technology',
    'home.solutions.autonomous': 'Autonomous Drones',
    'home.solutions.autonomous.desc': 'Intelligent aerial monitoring and data collection',
    'home.solutions.robotics': 'Smart Robotics',
    'home.solutions.robotics.desc': 'Automated farming operations and precision tasks',
    'home.solutions.iot': 'IoT Sensors',
    'home.solutions.iot.desc': 'Real-time environmental monitoring and alerts',
    'home.solutions.ai': 'AI Analytics',
    'home.solutions.ai.desc': 'Data-driven insights for optimal decision making',
    'home.solutions.viewAll': 'View All Solutions',
    
    'home.cta.title': 'Ready to Transform Your Farm?',
    'home.cta.subtitle': 'Join hundreds of forward-thinking farms using AgriBeacon to increase yields, reduce waste, and build a sustainable future.',
    'home.cta.demo': 'Schedule a Demo',
    'home.cta.learn': 'Learn More',
    
    // Navigation
    'nav.technology': 'Our Solutions',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact Us',
    'nav.login': 'Login',
    'nav.tryForFree': 'Try for FREE',
    'nav.contactSales': 'Contact Sales',
    
    // Technology menu
    'nav.technology.platform': 'Platform Overview',
    'nav.technology.ai': 'AI Analytics',
    'nav.technology.connectivity': 'Connectivity',
    'nav.technology.all': 'All Technology',
    
    // Resources menu
    'nav.resources.bestPractices': 'Best Practices',
    
    // About menu
    'nav.about.aboutUs': 'About Us',
    'nav.about.careers': 'Careers',
    'nav.about.contact': 'Contact',
    
    // Menu descriptions
    'nav.technology.platform.desc': 'Integrated B2B farm management',
    'nav.technology.ai.desc': 'Predictive insights for businesses',
    'nav.technology.connectivity.desc': 'LoRaWAN & Multi-network',
    'nav.technology.all.desc': 'Explore our tech stack',
    'nav.resources.bestPractices.desc': 'Farming guides & ESG',
    'nav.about.aboutUs.desc': 'Our mission & vision',
    'nav.about.careers.desc': 'Join our team',
    'nav.about.contact.desc': 'Get in touch',
    'nav.pricing.desc': 'B2B solutions & packages',
    
    // Footer
    'footer.company': 'Company',
    'footer.solutions': 'Solutions',
    'footer.technology': 'Technology',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2024 AgriBeacon. All rights reserved.',
    'footer.tagline': 'Precise signals. Smarter sensing. Sustainable growth. Empowering farmers with intelligent agricultural technology solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.documentation': 'Documentation',
    'footer.support': 'Support',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.builtFor': 'Built for sustainable agriculture.',
    
    // About Page
    'about.title': 'About AgriBeacon',
    'about.subtitle': 'Guiding the future of agriculture with intelligent technology',
    'about.vision.title': 'Our Vision',
    'about.vision.text1': 'To become the world\'s leading provider of intelligent, end-to-end agricultural technology solutions for perennial plant farms — enabling them to thrive economically, ecologically, and socially.',
    'about.vision.text2': 'We envision a resilient, data-driven farming future that champions sustainable growth, environmental responsibility, and long-term community impact — fully aligned with global ESG values.',
    'about.mission.title': 'Our Mission',
    'about.mission.text1': 'We empower farmers and agricultural businesses through a unified ecosystem of hardware and software — including autonomous drones, robotics, IoT sensors, and AI-powered analytics — to optimize every decision from soil to harvest.',
    'about.mission.text2': 'Our mission is to transform agriculture through precision, automation, and insight, delivering measurable impact to both people and planet.',
    'about.name.title': 'Why "AgriBeacon"?',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': 'Agriculture, the foundation of our focus and the heart of everything we do.',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': 'A guiding light or intelligent signal that shows the way forward.',
    'about.name.together': 'Together, the name reflects our commitment to providing clear direction, real-time insight, and smart automation in a complex and evolving farming environment.',
    'about.values.title': 'Our Core Values',
    'about.values.precision': 'Precision',
    'about.values.precision.desc': 'We believe in data-driven decisions and accurate measurements for optimal results.',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Constantly pushing boundaries with cutting-edge technology and fresh approaches.',
    'about.values.partnership': 'Partnership',
    'about.values.partnership.desc': 'Working hand-in-hand with farmers to understand and solve real challenges.',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability.desc': 'Building solutions that benefit both farms and the planet for generations to come.',
    'about.impact.title': 'Our Impact',
    'about.impact.farms': 'Active Farms',
    'about.impact.acres': 'Acres Monitored',
    'about.impact.yield': 'Avg. Yield Increase',
    'about.impact.water': 'Water Savings',
    
    // Careers Page
    'careers.title': 'AgriBeacon Careers',
    'careers.subtitle': 'Build the Future of Agriculture',
    'careers.description': 'Join our mission to transform farming with cutting-edge robotics, AI, and IoT technology. Make a real impact on food security and sustainability.',
    'careers.why.title': 'Why AgriBeacon?',
    'careers.why.subtitle': 'We\'re not just building technology—we\'re solving real problems for farmers across Southeast Asia.',
    'careers.benefits.impact': 'Real Impact',
    'careers.benefits.impact.desc': 'Your work directly helps farmers increase yields, reduce waste, and build sustainable operations.',
    'careers.benefits.tech': 'Cutting-Edge Tech',
    'careers.benefits.tech.desc': 'Work with autonomous drones, robotics, IoT sensors, and AI/ML in a challenging real-world domain.',
    'careers.benefits.growth': 'Growth & Equity',
    'careers.benefits.growth.desc': 'Join early, grow with us, and own part of what we\'re building through our equity program.',
    'careers.positions.title': 'Open Positions',
    'careers.positions.subtitle': 'We\'re looking for talented people who want to make a difference.',
    'careers.position.robotics.title': 'Robotics Engineer – Agricultural Automation',
    'careers.position.robotics.desc': 'Build autonomous robots and drones that are transforming how we grow food. Join us in making agriculture smarter, more sustainable, and more efficient.',
    'careers.position.location': 'Ha Noi',
    'careers.position.type.fulltime': 'Full-time',
    'careers.position.equity': 'Equity Available',
    'careers.position.onsite': 'Onsite',
    'careers.position.viewDetails': 'View Details',
    'careers.noRole.title': 'Don\'t See Your Role?',
    'careers.noRole.description': 'We\'re always looking for talented people. If you\'re passionate about agtech and innovation, reach out to us.',
    'careers.noRole.contact': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Ready to transform your farm? Let\'s discuss how AgriBeacon can help you grow smarter.',
    'contact.form.title': 'Request a Demo',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'John Doe',
    'contact.form.email': 'Email Address',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.phone': 'Phone Number',
    'contact.form.phone.placeholder': '+1 XXX XXX XXXX',
    'contact.form.farmSize': 'Farm Size (acres)',
    'contact.form.farmSize.placeholder': 'e.g., 200',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your farm business and what you\'re looking to achieve...',
    'contact.form.submit': 'Send Message',
    'contact.form.success.title': 'Message Sent!',
    'contact.form.success.description': 'Thank you for your interest. Our team will contact you within 24 hours.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.support.title': 'Support Hours',
    'contact.support.weekday': 'Monday - Friday: 8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': 'Saturday: 9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': 'Sunday: Closed',
    'contact.support.urgent': 'For urgent technical support, our 24/7 hotline is available for Enterprise partners.',
    
    // Contact Sales Dialog
    'contactSales.title': 'Contact Sales - B2B Solutions',
    'contactSales.description': 'Tell us about your farm and business needs, and our team will get back to you within 24 hours.',
    'contactSales.companyName': 'Company/Farm Name',
    'contactSales.companyName.placeholder': 'ABC Agricultural Co.',
    'contactSales.contactName': 'Contact Person',
    'contactSales.contactName.placeholder': 'John Doe',
    'contactSales.email': 'Business Email',
    'contactSales.email.placeholder': 'john@example.com',
    'contactSales.phone': 'Phone Number',
    'contactSales.phone.placeholder': '+1 XXX XXX XXXX',
    'contactSales.farmSize': 'Total Farm Size (acres)',
    'contactSales.farmSize.placeholder': 'e.g., 500',
    'contactSales.location': 'Farm Location',
    'contactSales.location.placeholder': 'Province/Region',
    'contactSales.cropTypes': 'Main Crop Types',
    'contactSales.cropTypes.placeholder': 'e.g., Rice, Coffee, Vegetables',
    'contactSales.challenges': 'Current Farming Challenges',
    'contactSales.challenges.placeholder': 'What challenges are you facing in your farming operations?',
    'contactSales.needs': 'Specific Needs & Solutions of Interest',
    'contactSales.needs.placeholder': 'Tell us about the solutions you\'re interested in (IoT sensors, drones, robotics, platform, etc.)',
    'contactSales.submit': 'Submit Inquiry',
    'contactSales.success.title': 'Opening Email Client',
    'contactSales.success.description': 'Your email client will open with the pre-filled information.',
    
    // Solutions/Pricing Page
    'solutions.title': 'Complete Solutions',
    'solutions.subtitle': 'Hardware + Software packages designed to transform your agricultural operations from day one',
    'solutions.platform.title': 'AgriBeacon Farm Management Platform',
    'solutions.platform.subtitle': 'Cloud-based SaaS platform included with every package. Monitor, analyze, and optimize your entire farm from anywhere.',
    'solutions.platform.feature1': 'Real-time Farm Dashboard',
    'solutions.platform.feature2': 'Predictive Analytics & Forecasting',
    'solutions.platform.feature3': 'Automated Alerts & Notifications',
    'solutions.platform.feature4': 'Historical Data & Trend Analysis',
    'solutions.platform.feature5': 'Resource Optimization Recommendations',
    'solutions.platform.feature6': 'Multi-farm Management',
    'solutions.platform.feature7': 'API Access for Integrations',
    'solutions.platform.feature8': 'Mobile & Desktop Applications',
    'solutions.badge.popular': 'Most Popular',
    'solutions.package.starter.name': 'Starter Package',
    'solutions.package.starter.price': 'Contact us',
    'solutions.package.starter.description': 'Perfect for small to medium farms starting their precision agriculture journey',
    'solutions.package.starter.feature1': '5 IoT Soil Sensors',
    'solutions.package.starter.feature2': 'Real-time monitoring dashboard',
    'solutions.package.starter.feature3': 'Basic weather integration',
    'solutions.package.starter.feature4': 'Mobile app access',
    'solutions.package.starter.feature5': 'Email support',
    'solutions.package.starter.feature6': 'Monthly analytics reports',
    'solutions.package.professional.name': 'Professional Package',
    'solutions.package.professional.price': 'Contact us',
    'solutions.package.professional.description': 'Complete solution for serious farmers ready to optimize operations',
    'solutions.package.professional.feature1': '15 IoT Multi-sensor stations',
    'solutions.package.professional.feature2': '1 Autonomous drone with AI vision',
    'solutions.package.professional.feature3': 'Advanced analytics & predictions',
    'solutions.package.professional.feature4': 'Automated irrigation control',
    'solutions.package.professional.feature5': 'Priority support & training',
    'solutions.package.professional.feature6': 'Custom integration options',
    'solutions.package.professional.feature7': 'Weekly optimization reports',
    'solutions.package.enterprise.name': 'Enterprise Package',
    'solutions.package.enterprise.price': 'Custom',
    'solutions.package.enterprise.description': 'Full-scale deployment for large agricultural operations',
    'solutions.package.enterprise.feature1': 'Unlimited sensor network',
    'solutions.package.enterprise.feature2': 'Multiple autonomous drones',
    'solutions.package.enterprise.feature3': 'Fleet of smart robots',
    'solutions.package.enterprise.feature4': 'Dedicated AI farm manager',
    'solutions.package.enterprise.feature5': '24/7 premium support',
    'solutions.package.enterprise.feature6': 'On-site installation & training',
    'solutions.package.enterprise.feature7': 'Custom software development',
    'solutions.package.enterprise.feature8': 'Real-time consultant access',
    'solutions.cta.title': 'Need Custom Solutions?',
    'solutions.cta.description': 'We work with farms of all sizes to create tailored solutions that meet your specific needs. Contact our team to discuss your requirements.',
    'solutions.cta.button': 'Contact Sales',
    'solutions.button.tryFree': 'Try for FREE',
    
    // Best Practices Page
    'bestPractices.badge': 'Knowledge Hub',
    'bestPractices.title': 'Best Practices',
    'bestPractices.subtitle': 'Modern farming strategies for sustainability, profitability, and environmental stewardship',
    
    // Tabs
    'bestPractices.tabs.circular': 'Circular Economy',
    'bestPractices.tabs.esg': 'ESG Framework',
    'bestPractices.tabs.technology': 'Technology',
    'bestPractices.tabs.farming': 'Farming Practices',
    
    // Circular Economy Tab
    'bestPractices.circular.title': 'Circular Economy for Modern Farms',
    'bestPractices.circular.description': 'Transform your farm into a closed-loop system where waste becomes a resource, reducing costs and environmental impact while improving resilience.',
    
    'bestPractices.circular.waste.title': 'Waste-to-Resource Systems',
    'bestPractices.circular.waste.description': 'Transform agricultural waste into valuable resources through composting, biogas production, and organic fertilizer creation.',
    'bestPractices.circular.waste.tip1': 'Implement on-farm composting systems for organic waste',
    'bestPractices.circular.waste.tip2': 'Convert crop residues into bioenergy or biochar',
    'bestPractices.circular.waste.tip3': 'Use animal waste for biogas and natural fertilizers',
    'bestPractices.circular.waste.tip4': 'Establish closed-loop nutrient cycles',
    
    'bestPractices.circular.water.title': 'Water Recycling & Reuse',
    'bestPractices.circular.water.description': 'Maximize water efficiency through recycling, rainwater harvesting, and precision irrigation systems.',
    'bestPractices.circular.water.tip1': 'Install rainwater collection and storage systems',
    'bestPractices.circular.water.tip2': 'Implement drip irrigation with moisture sensors',
    'bestPractices.circular.water.tip3': 'Reuse treated wastewater for non-food crops',
    'bestPractices.circular.water.tip4': 'Monitor and minimize water evaporation losses',
    
    'bestPractices.circular.regenerative.title': 'Regenerative Agriculture',
    'bestPractices.circular.regenerative.description': 'Build soil health and biodiversity while producing food, creating a self-sustaining ecosystem.',
    'bestPractices.circular.regenerative.tip1': 'Practice crop rotation and cover cropping',
    'bestPractices.circular.regenerative.tip2': 'Minimize soil disturbance with no-till methods',
    'bestPractices.circular.regenerative.tip3': 'Integrate livestock for natural fertilization',
    'bestPractices.circular.regenerative.tip4': 'Preserve and enhance biodiversity corridors',
    
    'bestPractices.circular.sharing.title': 'Resource Sharing Economy',
    'bestPractices.circular.sharing.description': 'Optimize equipment utilization and reduce costs through collaborative farming models.',
    'bestPractices.circular.sharing.tip1': 'Share expensive machinery with neighboring farms',
    'bestPractices.circular.sharing.tip2': 'Participate in cooperative buying programs',
    'bestPractices.circular.sharing.tip3': 'Exchange knowledge and best practices locally',
    'bestPractices.circular.sharing.tip4': 'Pool resources for bulk renewable energy investments',
    
    // ESG Framework Tab
    'bestPractices.esg.title': 'ESG Framework for Agriculture',
    'bestPractices.esg.description': 'Adopt Environmental, Social, and Governance principles to build a sustainable, responsible farm that meets modern investor and consumer expectations.',
    
    'bestPractices.esg.environmental': 'Environmental',
    'bestPractices.esg.env.carbon.title': 'Carbon Sequestration',
    'bestPractices.esg.env.carbon.description': 'Capture and store atmospheric CO2 through soil management and tree planting',
    'bestPractices.esg.env.carbon.metrics': 'Target: Net-zero or carbon-negative operations',
    
    'bestPractices.esg.env.biodiversity.title': 'Biodiversity Protection',
    'bestPractices.esg.env.biodiversity.description': 'Preserve native species, create wildlife habitats, and maintain ecological balance',
    'bestPractices.esg.env.biodiversity.metrics': 'Measure: Species diversity index and habitat area',
    
    'bestPractices.esg.env.energy.title': 'Clean Energy Transition',
    'bestPractices.esg.env.energy.description': 'Adopt solar, wind, and biogas to power farm operations sustainably',
    'bestPractices.esg.env.energy.metrics': 'Goal: 80%+ renewable energy by 2030',
    
    'bestPractices.esg.env.pollution.title': 'Pollution Prevention',
    'bestPractices.esg.env.pollution.description': 'Eliminate chemical runoff, reduce pesticide use, and minimize plastic waste',
    'bestPractices.esg.env.pollution.metrics': 'Track: Water quality and chemical usage reduction',
    
    'bestPractices.esg.social': 'Social',
    'bestPractices.esg.social.labor.title': 'Fair Labor Practices',
    'bestPractices.esg.social.labor.description': 'Ensure safe working conditions, fair wages, and worker well-being',
    'bestPractices.esg.social.labor.metrics': 'Certify: Fair Trade or equivalent standards',
    
    'bestPractices.esg.social.community.title': 'Community Engagement',
    'bestPractices.esg.social.community.description': 'Support local communities, create jobs, and contribute to regional development',
    'bestPractices.esg.social.community.metrics': 'Measure: Local employment rate and community investment',
    
    'bestPractices.esg.social.knowledge.title': 'Knowledge Transfer',
    'bestPractices.esg.social.knowledge.description': 'Train next-generation farmers and share sustainable practices',
    'bestPractices.esg.social.knowledge.metrics': 'Target: Annual training programs and apprenticeships',
    
    'bestPractices.esg.social.food.title': 'Food Security',
    'bestPractices.esg.social.food.description': 'Contribute to local and regional food availability and accessibility',
    'bestPractices.esg.social.food.metrics': 'Track: Production volume and distribution reach',
    
    'bestPractices.esg.governance': 'Governance',
    'bestPractices.esg.gov.reporting.title': 'Transparent Reporting',
    'bestPractices.esg.gov.reporting.description': 'Publish sustainability reports and share environmental impact data',
    'bestPractices.esg.gov.reporting.metrics': 'Annual ESG disclosure and third-party audits',
    
    'bestPractices.esg.gov.supply.title': 'Ethical Supply Chains',
    'bestPractices.esg.gov.supply.description': 'Partner with responsible suppliers and ensure traceability',
    'bestPractices.esg.gov.supply.metrics': '100% supplier compliance verification',
    
    'bestPractices.esg.gov.data.title': 'Data-Driven Decisions',
    'bestPractices.esg.gov.data.description': 'Use analytics and monitoring to guide sustainability improvements',
    'bestPractices.esg.gov.data.metrics': 'Real-time dashboards and quarterly reviews',
    
    'bestPractices.esg.gov.stakeholder.title': 'Stakeholder Engagement',
    'bestPractices.esg.gov.stakeholder.description': 'Involve farmers, investors, and communities in decision-making',
    'bestPractices.esg.gov.stakeholder.metrics': 'Regular stakeholder consultations and feedback loops',
    
    // Technology Tab
    'bestPractices.tech.title': 'Technology Best Practices',
    'bestPractices.tech.description': 'Leverage cutting-edge agricultural technology to optimize operations, reduce waste, and make data-driven decisions.',
    
    'bestPractices.tech.precision.title': 'Precision Agriculture',
    'bestPractices.tech.precision.description': 'Use data and technology to optimize inputs and maximize yields',
    'bestPractices.tech.precision.impl1': 'GPS-guided equipment for precise planting and spraying',
    'bestPractices.tech.precision.impl2': 'Variable rate technology (VRT) for fertilizer application',
    'bestPractices.tech.precision.impl3': 'Yield mapping to identify high and low-performing zones',
    'bestPractices.tech.precision.impl4': 'Soil sampling and analysis for targeted amendments',
    
    'bestPractices.tech.iot.title': 'IoT Sensor Networks',
    'bestPractices.tech.iot.description': 'Deploy connected sensors for real-time farm monitoring',
    'bestPractices.tech.iot.impl1': 'Soil moisture sensors for irrigation optimization',
    'bestPractices.tech.iot.impl2': 'Weather stations for microclimate tracking',
    'bestPractices.tech.iot.impl3': 'Livestock monitoring for health and behavior',
    'bestPractices.tech.iot.impl4': 'Equipment sensors for predictive maintenance',
    
    'bestPractices.tech.renewable.title': 'Renewable Energy Integration',
    'bestPractices.tech.renewable.description': 'Harness clean energy sources to power operations',
    'bestPractices.tech.renewable.impl1': 'Solar panels on barn roofs and unused land',
    'bestPractices.tech.renewable.impl2': 'Wind turbines in suitable locations',
    'bestPractices.tech.renewable.impl3': 'Biogas digesters for waste-to-energy conversion',
    'bestPractices.tech.renewable.impl4': 'Energy storage systems for 24/7 availability',
    
    'bestPractices.tech.ai.title': 'Data Analytics & AI',
    'bestPractices.tech.ai.description': 'Leverage artificial intelligence for predictive insights',
    'bestPractices.tech.ai.impl1': 'Crop disease prediction and early detection',
    'bestPractices.tech.ai.impl2': 'Yield forecasting based on historical and weather data',
    'bestPractices.tech.ai.impl3': 'Market price prediction for optimal selling times',
    'bestPractices.tech.ai.impl4': 'Automated decision support systems',
    
    // Farming Practices Tab
    'bestPractices.farming.title': 'Core Farming Best Practices',
    'bestPractices.farming.description': 'Time-tested and science-backed agricultural practices that form the foundation of successful, sustainable farming operations.',
    
    'bestPractices.farming.soil': 'Soil Health',
    'bestPractices.farming.soil.practice1': 'Test soil regularly (at least annually) for nutrient levels and pH',
    'bestPractices.farming.soil.practice2': 'Practice crop rotation to prevent nutrient depletion',
    'bestPractices.farming.soil.practice3': 'Use cover crops to prevent erosion and add organic matter',
    'bestPractices.farming.soil.practice4': 'Apply compost and organic amendments instead of synthetic fertilizers',
    'bestPractices.farming.soil.practice5': 'Minimize tillage to preserve soil structure and microbiomes',
    
    'bestPractices.farming.water': 'Water Management',
    'bestPractices.farming.water.practice1': 'Install drip or micro-sprinkler irrigation for efficiency',
    'bestPractices.farming.water.practice2': 'Schedule irrigation based on actual crop needs, not routines',
    'bestPractices.farming.water.practice3': 'Mulch around plants to reduce evaporation',
    'bestPractices.farming.water.practice4': 'Capture and store rainwater for dry periods',
    'bestPractices.farming.water.practice5': 'Monitor soil moisture continuously with sensors',
    
    'bestPractices.farming.pest': 'Pest & Disease Control',
    'bestPractices.farming.pest.practice1': 'Implement Integrated Pest Management (IPM) strategies',
    'bestPractices.farming.pest.practice2': 'Use biological controls (beneficial insects, microbes) first',
    'bestPractices.farming.pest.practice3': 'Scout fields regularly for early pest detection',
    'bestPractices.farming.pest.practice4': 'Rotate crops to break pest and disease cycles',
    'bestPractices.farming.pest.practice5': 'Choose disease-resistant varieties when available',
    
    'bestPractices.farming.crop': 'Crop Management',
    'bestPractices.farming.crop.practice1': 'Select varieties suited to your climate and soil',
    'bestPractices.farming.crop.practice2': 'Plant at optimal times based on weather and soil conditions',
    'bestPractices.farming.crop.practice3': 'Maintain proper spacing for air circulation and light',
    'bestPractices.farming.crop.practice4': 'Monitor growth stages and adjust inputs accordingly',
    'bestPractices.farming.crop.practice5': 'Harvest at peak maturity for maximum quality and shelf life',
    
    'bestPractices.farming.record': 'Record Keeping',
    'bestPractices.farming.record.practice1': 'Document all planting, treatment, and harvest activities',
    'bestPractices.farming.record.practice2': 'Track input costs and yields for profitability analysis',
    'bestPractices.farming.record.practice3': 'Maintain equipment maintenance logs',
    'bestPractices.farming.record.practice4': 'Record weather patterns and their impact on crops',
    'bestPractices.farming.record.practice5': 'Use farm management software for centralized data',
    
    // CTA Section
    'bestPractices.cta.title': 'Ready to Implement These Practices?',
    'bestPractices.cta.description': 'AgriBeacon\'s intelligent platform helps you track, measure, and optimize all these best practices with real-time data and actionable insights.',
    'bestPractices.cta.button1': 'Explore Solutions',
    'bestPractices.cta.button2': 'Get Expert Guidance',
    
    // Technology/Our Solutions Page
    'tech.title': 'Our Technology',
    'tech.subtitle': 'Cutting-edge hardware and intelligent software working in perfect harmony',
    
    // Platform Features
    'tech.platform.cloud': 'Cloud Platform',
    'tech.platform.cloud.desc': 'Secure, scalable infrastructure',
    'tech.platform.security': 'Data Security',
    'tech.platform.security.desc': 'Bank-level encryption',
    'tech.platform.network': 'Multi-Network',
    'tech.platform.network.desc': 'LoRaWAN, 4G, WiFi, Satellite',
    'tech.platform.energy': 'Energy Efficient',
    'tech.platform.energy.desc': 'Solar + long-life batteries',
    
    // Drones Tab
    'tech.drones.name': 'Autonomous Drones',
    'tech.drones.description': 'Advanced aerial intelligence for comprehensive farm monitoring and data collection',
    'tech.drones.spec1.label': 'Flight Time',
    'tech.drones.spec1.value': '45 minutes',
    'tech.drones.spec2.label': 'Coverage Area',
    'tech.drones.spec2.value': '200 acres/flight',
    'tech.drones.spec3.label': 'Camera Resolution',
    'tech.drones.spec3.value': '4K multispectral',
    'tech.drones.spec4.label': 'AI Processing',
    'tech.drones.spec4.value': 'Real-time onboard',
    'tech.drones.feature1': 'Autonomous flight planning and execution',
    'tech.drones.feature2': 'Multi-spectral imaging for crop health analysis',
    'tech.drones.feature3': 'Real-time pest and disease detection',
    'tech.drones.feature4': 'Precision spraying capabilities',
    'tech.drones.feature5': '3D terrain mapping',
    'tech.drones.feature6': 'Weather-resistant design (IP54)',
    
    // IoT Sensors Tab
    'tech.sensors.name': 'IoT Sensors',
    'tech.sensors.description': 'Comprehensive environmental monitoring with enterprise-grade reliability',
    'tech.sensors.spec1.label': 'Battery Life',
    'tech.sensors.spec1.value': '3+ years',
    'tech.sensors.spec2.label': 'Range',
    'tech.sensors.spec2.value': '10km LoRaWAN',
    'tech.sensors.spec3.label': 'Data Frequency',
    'tech.sensors.spec3.value': 'Every 15 minutes',
    'tech.sensors.spec4.label': 'Sensors per Unit',
    'tech.sensors.spec4.value': '8+ parameters',
    'tech.sensors.feature1': 'Soil moisture, temperature, and pH monitoring',
    'tech.sensors.feature2': 'Weather data (temp, humidity, rainfall, wind)',
    'tech.sensors.feature3': 'Light intensity and UV index tracking',
    'tech.sensors.feature4': 'Air quality and CO2 measurement',
    'tech.sensors.feature5': 'Solar-powered with backup battery',
    'tech.sensors.feature6': 'Waterproof and weatherproof (IP67)',
    
    // Robotics Tab
    'tech.robotics.name': 'Smart Robotics',
    'tech.robotics.description': 'Autonomous robotic systems for precision farming tasks and labor automation',
    'tech.robotics.spec1.label': 'Operating Time',
    'tech.robotics.spec1.value': '8-12 hours',
    'tech.robotics.spec2.label': 'Precision',
    'tech.robotics.spec2.value': '±2cm accuracy',
    'tech.robotics.spec3.label': 'Payload',
    'tech.robotics.spec3.value': '50kg capacity',
    'tech.robotics.spec4.label': 'Speed',
    'tech.robotics.spec4.value': '0.5-2 m/s',
    'tech.robotics.feature1': 'Automated weeding with 99% accuracy',
    'tech.robotics.feature2': 'Precision planting and seeding',
    'tech.robotics.feature3': 'Selective harvesting capabilities',
    'tech.robotics.feature4': 'Navigation via GPS + computer vision',
    'tech.robotics.feature5': 'Obstacle detection and avoidance',
    'tech.robotics.feature6': 'Autonomous charging and route planning',
    
    // AI Analytics Tab
    'tech.ai.name': 'AI Analytics',
    'tech.ai.description': 'Machine learning-powered insights and predictive analytics for optimal farm management',
    'tech.ai.spec1.label': 'Processing',
    'tech.ai.spec1.value': 'Cloud + Edge',
    'tech.ai.spec2.label': 'Predictions',
    'tech.ai.spec2.value': '7-30 day forecast',
    'tech.ai.spec3.label': 'Accuracy',
    'tech.ai.spec3.value': '92%+ average',
    'tech.ai.spec4.label': 'Data Points',
    'tech.ai.spec4.value': '1M+ daily',
    'tech.ai.feature1': 'Yield prediction and optimization',
    'tech.ai.feature2': 'Disease outbreak early warning system',
    'tech.ai.feature3': 'Irrigation scheduling recommendations',
    'tech.ai.feature4': 'Harvest timing optimization',
    'tech.ai.feature5': 'Resource allocation planning',
    'tech.ai.feature6': 'Historical trend analysis and benchmarking',
    
    'tech.keyFeatures': 'Key Features',
    'tech.integration.title': 'Seamless Integration',
    'tech.integration.description': 'All our technology works together through the AgriBeacon platform, providing a unified view of your farm operations with real-time data synchronization and intelligent automation.',
  },
  vi: {
    'home.hero.badge': 'Công nghệ nông nghiệp chính xác',
    'home.hero.title1': 'Tín hiệu chính xác.',
    'home.hero.title2': 'Cảm biến thông minh.',
    'home.hero.title3': 'Tăng trưởng bền vững.',
    'home.hero.subtitle': 'Chuyển đổi trang trại của bạn với các giải pháp công nghệ nông nghiệp thông minh, toàn diện. Tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'home.hero.explore': 'Khám phá giải pháp',
    'home.hero.demo': 'Yêu cầu demo',
    
    'home.vision.title': 'Tầm nhìn của chúng tôi',
    'home.vision.subtitle': 'Trở thành nhà cung cấp hàng đầu thế giới về các giải pháp công nghệ nông nghiệp thông minh, toàn diện cho các trang trại cây lâu năm — giúp họ phát triển mạnh về kinh tế, sinh thái và xã hội.',
    'home.mission.title': 'Sứ mệnh của chúng tôi',
    'home.mission.text1': 'Chúng tôi trao quyền cho nông dân và doanh nghiệp nông nghiệp thông qua hệ sinh thái thống nhất của phần cứng và phần mềm — bao gồm máy bay không người lái tự động, robot, cảm biến IoT và phân tích AI — để tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'home.mission.text2': 'Sứ mệnh của chúng tôi là chuyển đổi nông nghiệp thông qua độ chính xác, tự động hóa và thông tin chi tiết, mang lại tác động có thể đo lường được cho cả con người và hành tinh.',
    'home.stats.farms': 'Trang trại được tối ưu',
    'home.stats.data': 'Điểm dữ liệu hàng ngày',
    'home.stats.yield': 'Tăng năng suất',
    'home.stats.water': 'Tiết kiệm nước',
    
    'home.solutions.title': 'Giải pháp thông minh',
    'home.solutions.subtitle': 'Hệ sinh thái hoàn chỉnh của công nghệ nông nghiệp tiên tiến',
    'home.solutions.autonomous': 'Máy bay không người lái tự động',
    'home.solutions.autonomous.desc': 'Giám sát trên không thông minh và thu thập dữ liệu',
    'home.solutions.robotics': 'Robot thông minh',
    'home.solutions.robotics.desc': 'Hoạt động nông nghiệp tự động và nhiệm vụ chính xác',
    'home.solutions.iot': 'Cảm biến IoT',
    'home.solutions.iot.desc': 'Giám sát môi trường thời gian thực và cảnh báo',
    'home.solutions.ai': 'Phân tích AI',
    'home.solutions.ai.desc': 'Thông tin chi tiết dựa trên dữ liệu để ra quyết định tối ưu',
    'home.solutions.viewAll': 'Xem tất cả giải pháp',
    
    'home.cta.title': 'Sẵn sàng chuyển đổi trang trại của bạn?',
    'home.cta.subtitle': 'Tham gia cùng hàng trăm trang trại có tầm nhìn xa sử dụng AgriBeacon để tăng năng suất, giảm lãng phí và xây dựng tương lai bền vững.',
    'home.cta.demo': 'Đặt lịch demo',
    'home.cta.learn': 'Tìm hiểu thêm',
    
    // Navigation
    'nav.technology': 'Giải pháp của chúng tôi',
    'nav.resources': 'Tài nguyên',
    'nav.pricing': 'Bảng giá',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'nav.tryForFree': 'Dùng thử MIỄN PHÍ',
    'nav.contactSales': 'Liên hệ bán hàng',
    
    // Technology menu
    'nav.technology.platform': 'Tổng quan nền tảng',
    'nav.technology.ai': 'Phân tích AI',
    'nav.technology.connectivity': 'Kết nối',
    'nav.technology.all': 'Tất cả công nghệ',
    
    // Resources menu
    'nav.resources.bestPractices': 'Thực hành tốt nhất',
    
    // About menu
    'nav.about.aboutUs': 'Về chúng tôi',
    'nav.about.careers': 'Tuyển dụng',
    'nav.about.contact': 'Liên hệ',
    
    // Menu descriptions
    'nav.technology.platform.desc': 'Quản lý trang trại B2B tích hợp',
    'nav.technology.ai.desc': 'Phân tích dự đoán cho doanh nghiệp',
    'nav.technology.connectivity.desc': 'LoRaWAN & Đa mạng',
    'nav.technology.all.desc': 'Khám phá ngăn xếp công nghệ',
    'nav.resources.bestPractices.desc': 'Hướng dẫn nông nghiệp & ESG',
    'nav.about.aboutUs.desc': 'Sứ mệnh & tầm nhìn',
    'nav.about.careers.desc': 'Tham gia đội ngũ',
    'nav.about.contact.desc': 'Liên hệ với chúng tôi',
    'nav.pricing.desc': 'Giải pháp & gói B2B',
    
    // Footer
    'footer.company': 'Công ty',
    'footer.solutions': 'Giải pháp',
    'footer.technology': 'Công nghệ',
    'footer.resources': 'Tài nguyên',
    'footer.legal': 'Pháp lý',
    'footer.copyright': '© 2024 AgriBeacon. Tất cả quyền được bảo lưu.',
    'footer.tagline': 'Tín hiệu chính xác. Cảm biến thông minh. Tăng trưởng bền vững. Trao quyền cho nông dân với các giải pháp công nghệ nông nghiệp thông minh.',
    'footer.quickLinks': 'Liên kết nhanh',
    'footer.documentation': 'Tài liệu',
    'footer.support': 'Hỗ trợ',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.builtFor': 'Xây dựng cho nông nghiệp bền vững.',
    
    // About Page
    'about.title': 'Về AgriBeacon',
    'about.subtitle': 'Dẫn dắt tương lai nông nghiệp với công nghệ thông minh',
    'about.vision.title': 'Tầm nhìn của chúng tôi',
    'about.vision.text1': 'Trở thành nhà cung cấp hàng đầu thế giới về các giải pháp công nghệ nông nghiệp thông minh, toàn diện cho các trang trại cây lâu năm — giúp họ phát triển mạnh về kinh tế, sinh thái và xã hội.',
    'about.vision.text2': 'Chúng tôi hình dung một tương lai nông nghiệp kiên cường, dựa trên dữ liệu, ủng hộ tăng trưởng bền vững, trách nhiệm môi trường và tác động cộng đồng lâu dài — hoàn toàn phù hợp với các giá trị ESG toàn cầu.',
    'about.mission.title': 'Sứ mệnh của chúng tôi',
    'about.mission.text1': 'Chúng tôi trao quyền cho nông dân và doanh nghiệp nông nghiệp thông qua hệ sinh thái thống nhất của phần cứng và phần mềm — bao gồm máy bay không người lái tự động, robot, cảm biến IoT và phân tích AI — để tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'about.mission.text2': 'Sứ mệnh của chúng tôi là chuyển đổi nông nghiệp thông qua độ chính xác, tự động hóa và thông tin chi tiết, mang lại tác động có thể đo lường được cho cả con người và hành tinh.',
    'about.name.title': 'Tại sao là "AgriBeacon"?',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': 'Nông nghiệp, nền tảng trọng tâm và trái tim của mọi việc chúng tôi làm.',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': 'Ngọn đèn dẫn đường hoặc tín hiệu thông minh chỉ đường phía trước.',
    'about.name.together': 'Cùng nhau, tên gọi phản ánh cam kết của chúng tôi trong việc cung cấp hướng đi rõ ràng, thông tin chi tiết thời gian thực và tự động hóa thông minh trong môi trường canh tác phức tạp và luôn thay đổi.',
    'about.values.title': 'Giá trị cốt lõi',
    'about.values.precision': 'Chính xác',
    'about.values.precision.desc': 'Chúng tôi tin vào các quyết định dựa trên dữ liệu và đo lường chính xác để đạt kết quả tối ưu.',
    'about.values.innovation': 'Đổi mới',
    'about.values.innovation.desc': 'Liên tục vượt qua ranh giới với công nghệ tiên tiến và cách tiếp cận mới mẻ.',
    'about.values.partnership': 'Đối tác',
    'about.values.partnership.desc': 'Làm việc sát cánh với nông dân để hiểu và giải quyết các thách thức thực tế.',
    'about.values.sustainability': 'Bền vững',
    'about.values.sustainability.desc': 'Xây dựng các giải pháp mang lại lợi ích cho cả trang trại và hành tinh cho các thế hệ tương lai.',
    'about.impact.title': 'Tác động của chúng tôi',
    'about.impact.farms': 'Trang trại hoạt động',
    'about.impact.acres': 'Diện tích giám sát',
    'about.impact.yield': 'Tăng năng suất trung bình',
    'about.impact.water': 'Tiết kiệm nước',
    
    // Careers Page
    'careers.title': 'Tuyển dụng AgriBeacon',
    'careers.subtitle': 'Xây dựng tương lai nông nghiệp',
    'careers.description': 'Tham gia sứ mệnh của chúng tôi để chuyển đổi nông nghiệp với công nghệ robot, AI và IoT tiên tiến. Tạo ra tác động thực sự đến an ninh lương thực và tính bền vững.',
    'careers.why.title': 'Tại sao chọn AgriBeacon?',
    'careers.why.subtitle': 'Chúng tôi không chỉ xây dựng công nghệ—chúng tôi giải quyết các vấn đề thực tế cho nông dân trên khắp Đông Nam Á.',
    'careers.benefits.impact': 'Tác động thực sự',
    'careers.benefits.impact.desc': 'Công việc của bạn trực tiếp giúp nông dân tăng năng suất, giảm lãng phí và xây dựng hoạt động bền vững.',
    'careers.benefits.tech': 'Công nghệ tiên tiến',
    'careers.benefits.tech.desc': 'Làm việc với máy bay không người lái tự động, robot, cảm biến IoT và AI/ML trong lĩnh vực thực tế đầy thách thức.',
    'careers.benefits.growth': 'Tăng trưởng & Cổ phần',
    'careers.benefits.growth.desc': 'Tham gia sớm, phát triển cùng chúng tôi và sở hữu một phần những gì chúng tôi đang xây dựng thông qua chương trình cổ phần.',
    'careers.positions.title': 'Vị trí tuyển dụng',
    'careers.positions.subtitle': 'Chúng tôi đang tìm kiếm những người tài năng muốn tạo ra sự khác biệt.',
    'careers.position.robotics.title': 'Kỹ sư Robot – Tự động hóa nông nghiệp',
    'careers.position.robotics.desc': 'Xây dựng robot và máy bay không người lái tự động đang chuyển đổi cách chúng ta trồng trọt. Tham gia cùng chúng tôi để làm cho nông nghiệp thông minh hơn, bền vững hơn và hiệu quả hơn.',
    'careers.position.location': 'Hà Nội',
    'careers.position.type.fulltime': 'Toàn thời gian',
    'careers.position.equity': 'Có cổ phần',
    'careers.position.onsite': 'Làm việc tại văn phòng',
    'careers.position.viewDetails': 'Xem chi tiết',
    'careers.noRole.title': 'Không tìm thấy vị trí phù hợp?',
    'careers.noRole.description': 'Chúng tôi luôn tìm kiếm những người tài năng. Nếu bạn đam mê công nghệ nông nghiệp và đổi mới, hãy liên hệ với chúng tôi.',
    'careers.noRole.contact': 'Liên hệ chúng tôi',
    
    // Contact Page
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Sẵn sàng chuyển đổi trang trại của bạn? Hãy thảo luận về cách AgriBeacon có thể giúp bạn phát triển thông minh hơn.',
    'contact.form.title': 'Yêu cầu demo',
    'contact.form.name': 'Họ và tên',
    'contact.form.name.placeholder': 'Nguyễn Văn A',
    'contact.form.email': 'Địa chỉ email',
    'contact.form.email.placeholder': 'nguyenvana@example.com',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.phone.placeholder': '+84 XXX XXX XXX',
    'contact.form.farmSize': 'Diện tích trang trại (hecta)',
    'contact.form.farmSize.placeholder': 'ví dụ: 200',
    'contact.form.message': 'Tin nhắn',
    'contact.form.message.placeholder': 'Hãy cho chúng tôi biết về hoạt động nông nghiệp của bạn và những gì bạn muốn đạt được...',
    'contact.form.submit': 'Gửi tin nhắn',
    'contact.form.success.title': 'Đã gửi tin nhắn!',
    'contact.form.success.description': 'Cảm ơn bạn đã quan tâm. Đội ngũ của chúng tôi sẽ liên hệ với bạn trong vòng 24 giờ.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Điện thoại',
    'contact.info.location': 'Địa chỉ',
    'contact.support.title': 'Giờ hỗ trợ',
    'contact.support.weekday': 'Thứ Hai - Thứ Sáu: 8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': 'Thứ Bảy: 9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': 'Chủ Nhật: Nghỉ',
    'contact.support.urgent': 'Đối với hỗ trợ kỹ thuật khẩn cấp, đường dây nóng 24/7 của chúng tôi có sẵn cho các đối tác Doanh nghiệp.',
    
    // Contact Sales Dialog
    'contactSales.title': 'Liên hệ bán hàng - Giải pháp B2B',
    'contactSales.description': 'Hãy cho chúng tôi biết về trang trại và nhu cầu kinh doanh của bạn, đội ngũ của chúng tôi sẽ liên hệ lại trong vòng 24 giờ.',
    'contactSales.companyName': 'Tên công ty/Trang trại',
    'contactSales.companyName.placeholder': 'Công ty Nông nghiệp ABC',
    'contactSales.contactName': 'Người liên hệ',
    'contactSales.contactName.placeholder': 'Nguyễn Văn A',
    'contactSales.email': 'Email doanh nghiệp',
    'contactSales.email.placeholder': 'nguyenvana@example.com',
    'contactSales.phone': 'Số điện thoại',
    'contactSales.phone.placeholder': '+84 XXX XXX XXX',
    'contactSales.farmSize': 'Tổng diện tích trang trại (hecta)',
    'contactSales.farmSize.placeholder': 'ví dụ: 500',
    'contactSales.location': 'Vị trí trang trại',
    'contactSales.location.placeholder': 'Tỉnh/Khu vực',
    'contactSales.cropTypes': 'Loại cây trồng chính',
    'contactSales.cropTypes.placeholder': 'ví dụ: Lúa, Cà phê, Rau củ',
    'contactSales.challenges': 'Thách thức hiện tại trong canh tác',
    'contactSales.challenges.placeholder': 'Bạn đang gặp những thách thức gì trong hoạt động canh tác của mình?',
    'contactSales.needs': 'Nhu cầu cụ thể & Giải pháp quan tâm',
    'contactSales.needs.placeholder': 'Hãy cho chúng tôi biết về các giải pháp bạn quan tâm (cảm biến IoT, máy bay không người lái, robot, nền tảng, v.v.)',
    'contactSales.submit': 'Gửi yêu cầu',
    'contactSales.success.title': 'Đang mở ứng dụng Email',
    'contactSales.success.description': 'Ứng dụng email của bạn sẽ mở với thông tin đã được điền sẵn.',
    
    // Solutions/Pricing Page
    'solutions.title': 'Giải pháp toàn diện',
    'solutions.subtitle': 'Gói phần cứng + Phần mềm được thiết kế để chuyển đổi hoạt động nông nghiệp của bạn ngay từ ngày đầu tiên',
    'solutions.platform.title': 'Nền tảng quản lý trang trại AgriBeacon',
    'solutions.platform.subtitle': 'Nền tảng SaaS trên đám mây được bao gồm trong mọi gói. Giám sát, phân tích và tối ưu hóa toàn bộ trang trại của bạn từ mọi nơi.',
    'solutions.platform.feature1': 'Bảng điều khiển trang trại thời gian thực',
    'solutions.platform.feature2': 'Phân tích dự đoán & Dự báo',
    'solutions.platform.feature3': 'Cảnh báo & Thông báo tự động',
    'solutions.platform.feature4': 'Phân tích dữ liệu lịch sử & Xu hướng',
    'solutions.platform.feature5': 'Đề xuất tối ưu hóa tài nguyên',
    'solutions.platform.feature6': 'Quản lý đa trang trại',
    'solutions.platform.feature7': 'Truy cập API để tích hợp',
    'solutions.platform.feature8': 'Ứng dụng di động & Máy tính',
    'solutions.badge.popular': 'Phổ biến nhất',
    'solutions.package.starter.name': 'Gói khởi đầu',
    'solutions.package.starter.price': 'Liên hệ',
    'solutions.package.starter.description': 'Hoàn hảo cho các trang trại vừa và nhỏ bắt đầu hành trình nông nghiệp chính xác',
    'solutions.package.starter.feature1': '5 cảm biến đất IoT',
    'solutions.package.starter.feature2': 'Bảng điều khiển giám sát thời gian thực',
    'solutions.package.starter.feature3': 'Tích hợp thời tiết cơ bản',
    'solutions.package.starter.feature4': 'Truy cập ứng dụng di động',
    'solutions.package.starter.feature5': 'Hỗ trợ qua email',
    'solutions.package.starter.feature6': 'Báo cáo phân tích hàng tháng',
    'solutions.package.professional.name': 'Gói chuyên nghiệp',
    'solutions.package.professional.price': 'Liên hệ',
    'solutions.package.professional.description': 'Giải pháp hoàn chỉnh cho nông dân nghiêm túc sẵn sàng tối ưu hóa hoạt động',
    'solutions.package.professional.feature1': '15 trạm đa cảm biến IoT',
    'solutions.package.professional.feature2': '1 máy bay không người lái tự động với tầm nhìn AI',
    'solutions.package.professional.feature3': 'Phân tích & Dự đoán nâng cao',
    'solutions.package.professional.feature4': 'Kiểm soát tưới tiêu tự động',
    'solutions.package.professional.feature5': 'Hỗ trợ & Đào tạo ưu tiên',
    'solutions.package.professional.feature6': 'Tùy chọn tích hợp tùy chỉnh',
    'solutions.package.professional.feature7': 'Báo cáo tối ưu hóa hàng tuần',
    'solutions.package.enterprise.name': 'Gói doanh nghiệp',
    'solutions.package.enterprise.price': 'Tùy chỉnh',
    'solutions.package.enterprise.description': 'Triển khai quy mô lớn cho các hoạt động nông nghiệp quy mô lớn',
    'solutions.package.enterprise.feature1': 'Mạng cảm biến không giới hạn',
    'solutions.package.enterprise.feature2': 'Nhiều máy bay không người lái tự động',
    'solutions.package.enterprise.feature3': 'Đội robot thông minh',
    'solutions.package.enterprise.feature4': 'Quản lý trang trại AI chuyên dụng',
    'solutions.package.enterprise.feature5': 'Hỗ trợ cao cấp 24/7',
    'solutions.package.enterprise.feature6': 'Cài đặt & Đào tạo tại chỗ',
    'solutions.package.enterprise.feature7': 'Phát triển phần mềm tùy chỉnh',
    'solutions.package.enterprise.feature8': 'Truy cập chuyên gia tư vấn thời gian thực',
    'solutions.cta.title': 'Cần giải pháp tùy chỉnh?',
    'solutions.cta.description': 'Chúng tôi làm việc với các trang trại ở mọi quy mô để tạo ra các giải pháp phù hợp đáp ứng nhu cầu cụ thể của bạn. Liên hệ với đội ngũ của chúng tôi để thảo luận về yêu cầu của bạn.',
    'solutions.cta.button': 'Liên hệ bán hàng',
    'solutions.button.tryFree': 'Dùng thử MIỄN PHÍ',
    
    // Best Practices Page
    'bestPractices.badge': 'Trung tâm kiến thức',
    'bestPractices.title': 'Thực hành tốt nhất',
    'bestPractices.subtitle': 'Chiến lược canh tác hiện đại cho sự bền vững, lợi nhuận và bảo vệ môi trường',
    
    // Tabs
    'bestPractices.tabs.circular': 'Kinh tế tuần hoàn',
    'bestPractices.tabs.esg': 'Khung ESG',
    'bestPractices.tabs.technology': 'Công nghệ',
    'bestPractices.tabs.farming': 'Thực hành canh tác',
    
    // Circular Economy Tab
    'bestPractices.circular.title': 'Kinh tế tuần hoàn cho trang trại hiện đại',
    'bestPractices.circular.description': 'Biến trang trại của bạn thành một hệ thống khép kín, nơi chất thải trở thành tài nguyên, giảm chi phí và tác động môi trường đồng thời cải thiện khả năng phục hồi.',
    
    'bestPractices.circular.waste.title': 'Hệ thống chuyển đổi chất thải thành tài nguyên',
    'bestPractices.circular.waste.description': 'Biến chất thải nông nghiệp thành tài nguyên có giá trị thông qua ủ phân, sản xuất khí sinh học và tạo phân bón hữu cơ.',
    'bestPractices.circular.waste.tip1': 'Triển khai hệ thống ủ phân trong trang trại cho chất thải hữu cơ',
    'bestPractices.circular.waste.tip2': 'Chuyển đổi phế phẩm cây trồng thành năng lượng sinh học hoặc than sinh học',
    'bestPractices.circular.waste.tip3': 'Sử dụng chất thải động vật để sản xuất khí sinh học và phân bón tự nhiên',
    'bestPractices.circular.waste.tip4': 'Thiết lập chu trình dinh dưỡng khép kín',
    
    'bestPractices.circular.water.title': 'Tái chế & Tái sử dụng nước',
    'bestPractices.circular.water.description': 'Tối đa hóa hiệu quả sử dụng nước thông qua tái chế, thu hoạch nước mưa và hệ thống tưới tiêu chính xác.',
    'bestPractices.circular.water.tip1': 'Lắp đặt hệ thống thu gom và lưu trữ nước mưa',
    'bestPractices.circular.water.tip2': 'Triển khai tưới nhỏ giọt với cảm biến độ ẩm',
    'bestPractices.circular.water.tip3': 'Tái sử dụng nước thải đã xử lý cho cây trồng phi thực phẩm',
    'bestPractices.circular.water.tip4': 'Giám sát và giảm thiểu tổn thất nước do bốc hơi',
    
    'bestPractices.circular.regenerative.title': 'Nông nghiệp tái sinh',
    'bestPractices.circular.regenerative.description': 'Xây dựng sức khỏe đất và đa dạng sinh học trong khi sản xuất thực phẩm, tạo ra một hệ sinh thái tự duy trì.',
    'bestPractices.circular.regenerative.tip1': 'Thực hành luân canh và trồng cây phủ',
    'bestPractices.circular.regenerative.tip2': 'Giảm thiểu xáo trộn đất bằng phương pháp không cày',
    'bestPractices.circular.regenerative.tip3': 'Tích hợp chăn nuôi để bón phân tự nhiên',
    'bestPractices.circular.regenerative.tip4': 'Bảo tồn và tăng cường hành lang đa dạng sinh học',
    
    'bestPractices.circular.sharing.title': 'Kinh tế chia sẻ tài nguyên',
    'bestPractices.circular.sharing.description': 'Tối ưu hóa việc sử dụng thiết bị và giảm chi phí thông qua mô hình canh tác hợp tác.',
    'bestPractices.circular.sharing.tip1': 'Chia sẻ máy móc đắt tiền với các trang trại lân cận',
    'bestPractices.circular.sharing.tip2': 'Tham gia chương trình mua sắm hợp tác',
    'bestPractices.circular.sharing.tip3': 'Trao đổi kiến thức và thực hành tốt nhất tại địa phương',
    'bestPractices.circular.sharing.tip4': 'Gộp nguồn lực để đầu tư năng lượng tái tạo số lượng lớn',
    
    // ESG Framework Tab
    'bestPractices.esg.title': 'Khung ESG cho Nông nghiệp',
    'bestPractices.esg.description': 'Áp dụng các nguyên tắc Môi trường, Xã hội và Quản trị để xây dựng một trang trại bền vững, có trách nhiệm đáp ứng kỳ vọng của nhà đầu tư và người tiêu dùng hiện đại.',
    
    'bestPractices.esg.environmental': 'Môi trường',
    'bestPractices.esg.env.carbon.title': 'Cô lập Carbon',
    'bestPractices.esg.env.carbon.description': 'Bắt giữ và lưu trữ CO2 trong khí quyển thông qua quản lý đất và trồng cây',
    'bestPractices.esg.env.carbon.metrics': 'Mục tiêu: Hoạt động carbon trung hòa hoặc carbon âm',
    
    'bestPractices.esg.env.biodiversity.title': 'Bảo vệ đa dạng sinh học',
    'bestPractices.esg.env.biodiversity.description': 'Bảo tồn các loài bản địa, tạo môi trường sống cho động vật hoang dã và duy trì cân bằng sinh thái',
    'bestPractices.esg.env.biodiversity.metrics': 'Đo lường: Chỉ số đa dạng loài và diện tích môi trường sống',
    
    'bestPractices.esg.env.energy.title': 'Chuyển đổi năng lượng sạch',
    'bestPractices.esg.env.energy.description': 'Áp dụng năng lượng mặt trời, gió và khí sinh học để vận hành trang trại bền vững',
    'bestPractices.esg.env.energy.metrics': 'Mục tiêu: 80%+ năng lượng tái tạo vào năm 2030',
    
    'bestPractices.esg.env.pollution.title': 'Ngăn ngừa ô nhiễm',
    'bestPractices.esg.env.pollution.description': 'Loại bỏ dòng chảy hóa chất, giảm sử dụng thuốc trừ sâu và giảm thiểu chất thải nhựa',
    'bestPractices.esg.env.pollution.metrics': 'Theo dõi: Chất lượng nước và giảm sử dụng hóa chất',
    
    'bestPractices.esg.social': 'Xã hội',
    'bestPractices.esg.social.labor.title': 'Thực hành lao động công bằng',
    'bestPractices.esg.social.labor.description': 'Đảm bảo điều kiện làm việc an toàn, mức lương công bằng và phúc lợi người lao động',
    'bestPractices.esg.social.labor.metrics': 'Chứng nhận: Fair Trade hoặc tiêu chuẩn tương đương',
    
    'bestPractices.esg.social.community.title': 'Gắn kết cộng đồng',
    'bestPractices.esg.social.community.description': 'Hỗ trợ cộng đồng địa phương, tạo việc làm và đóng góp vào phát triển khu vực',
    'bestPractices.esg.social.community.metrics': 'Đo lường: Tỷ lệ việc làm địa phương và đầu tư cộng đồng',
    
    'bestPractices.esg.social.knowledge.title': 'Chuyển giao kiến thức',
    'bestPractices.esg.social.knowledge.description': 'Đào tạo nông dân thế hệ tiếp theo và chia sẻ các thực hành bền vững',
    'bestPractices.esg.social.knowledge.metrics': 'Mục tiêu: Chương trình đào tạo hàng năm và học việc',
    
    'bestPractices.esg.social.food.title': 'An ninh lương thực',
    'bestPractices.esg.social.food.description': 'Đóng góp vào khả năng cung cấp và tiếp cận thực phẩm tại địa phương và khu vực',
    'bestPractices.esg.social.food.metrics': 'Theo dõi: Khối lượng sản xuất và phạm vi phân phối',
    
    'bestPractices.esg.governance': 'Quản trị',
    'bestPractices.esg.gov.reporting.title': 'Báo cáo minh bạch',
    'bestPractices.esg.gov.reporting.description': 'Công bố báo cáo bền vững và chia sẻ dữ liệu tác động môi trường',
    'bestPractices.esg.gov.reporting.metrics': 'Công bố ESG hàng năm và kiểm toán bên thứ ba',
    
    'bestPractices.esg.gov.supply.title': 'Chuỗi cung ứng đạo đức',
    'bestPractices.esg.gov.supply.description': 'Hợp tác với nhà cung cấp có trách nhiệm và đảm bảo khả năng truy xuất nguồn gốc',
    'bestPractices.esg.gov.supply.metrics': 'Xác minh tuân thủ 100% nhà cung cấp',
    
    'bestPractices.esg.gov.data.title': 'Quyết định dựa trên dữ liệu',
    'bestPractices.esg.gov.data.description': 'Sử dụng phân tích và giám sát để hướng dẫn cải thiện bền vững',
    'bestPractices.esg.gov.data.metrics': 'Bảng điều khiển thời gian thực và đánh giá hàng quý',
    
    'bestPractices.esg.gov.stakeholder.title': 'Gắn kết các bên liên quan',
    'bestPractices.esg.gov.stakeholder.description': 'Lôi cuốn nông dân, nhà đầu tư và cộng đồng vào việc ra quyết định',
    'bestPractices.esg.gov.stakeholder.metrics': 'Tham vấn định kỳ các bên liên quan và vòng phản hồi',
    
    // Technology Tab
    'bestPractices.tech.title': 'Thực hành tốt nhất về Công nghệ',
    'bestPractices.tech.description': 'Tận dụng công nghệ nông nghiệp tiên tiến để tối ưu hóa hoạt động, giảm lãng phí và đưa ra quyết định dựa trên dữ liệu.',
    
    'bestPractices.tech.precision.title': 'Nông nghiệp chính xác',
    'bestPractices.tech.precision.description': 'Sử dụng dữ liệu và công nghệ để tối ưu hóa đầu vào và tối đa hóa năng suất',
    'bestPractices.tech.precision.impl1': 'Thiết bị dẫn đường GPS để gieo trồng và phun thuốc chính xác',
    'bestPractices.tech.precision.impl2': 'Công nghệ tỷ lệ thay đổi (VRT) để bón phân',
    'bestPractices.tech.precision.impl3': 'Lập bản đồ năng suất để xác định các khu vực hiệu suất cao và thấp',
    'bestPractices.tech.precision.impl4': 'Lấy mẫu và phân tích đất để cải tạo có mục tiêu',
    
    'bestPractices.tech.iot.title': 'Mạng cảm biến IoT',
    'bestPractices.tech.iot.description': 'Triển khai cảm biến kết nối để giám sát trang trại thời gian thực',
    'bestPractices.tech.iot.impl1': 'Cảm biến độ ẩm đất để tối ưu hóa tưới tiêu',
    'bestPractices.tech.iot.impl2': 'Trạm thời tiết để theo dõi vi khí hậu',
    'bestPractices.tech.iot.impl3': 'Giám sát vật nuôi về sức khỏe và hành vi',
    'bestPractices.tech.iot.impl4': 'Cảm biến thiết bị để bảo trì dự đoán',
    
    'bestPractices.tech.renewable.title': 'Tích hợp năng lượng tái tạo',
    'bestPractices.tech.renewable.description': 'Khai thác các nguồn năng lượng sạch để vận hành',
    'bestPractices.tech.renewable.impl1': 'Tấm pin mặt trời trên mái nhà kho và đất không sử dụng',
    'bestPractices.tech.renewable.impl2': 'Tuabin gió ở các vị trí phù hợp',
    'bestPractices.tech.renewable.impl3': 'Bể khí sinh học để chuyển đổi chất thải thành năng lượng',
    'bestPractices.tech.renewable.impl4': 'Hệ thống lưu trữ năng lượng cho khả năng cung cấp 24/7',
    
    'bestPractices.tech.ai.title': 'Phân tích dữ liệu & AI',
    'bestPractices.tech.ai.description': 'Tận dụng trí tuệ nhân tạo để có những hiểu biết dự đoán',
    'bestPractices.tech.ai.impl1': 'Dự đoán bệnh cây trồng và phát hiện sớm',
    'bestPractices.tech.ai.impl2': 'Dự báo năng suất dựa trên dữ liệu lịch sử và thời tiết',
    'bestPractices.tech.ai.impl3': 'Dự đoán giá thị trường để có thời điểm bán tối ưu',
    'bestPractices.tech.ai.impl4': 'Hệ thống hỗ trợ quyết định tự động',
    
    // Farming Practices Tab
    'bestPractices.farming.title': 'Thực hành canh tác cốt lõi tốt nhất',
    'bestPractices.farming.description': 'Các thực hành nông nghiệp đã được kiểm chứng theo thời gian và được khoa học ủng hộ, tạo nền tảng cho hoạt động canh tác thành công và bền vững.',
    
    'bestPractices.farming.soil': 'Sức khỏe đất',
    'bestPractices.farming.soil.practice1': 'Kiểm tra đất định kỳ (ít nhất hàng năm) về mức dinh dưỡng và pH',
    'bestPractices.farming.soil.practice2': 'Thực hành luân canh để ngăn chặn suy giảm dinh dưỡng',
    'bestPractices.farming.soil.practice3': 'Sử dụng cây phủ để ngăn xói mòn và thêm chất hữu cơ',
    'bestPractices.farming.soil.practice4': 'Bón phân compost và chất hữu cơ thay vì phân bón tổng hợp',
    'bestPractices.farming.soil.practice5': 'Giảm thiểu cày xới để bảo tồn cấu trúc đất và vi sinh vật',
    
    'bestPractices.farming.water': 'Quản lý nước',
    'bestPractices.farming.water.practice1': 'Lắp đặt tưới nhỏ giọt hoặc phun sương nhỏ để hiệu quả',
    'bestPractices.farming.water.practice2': 'Lên lịch tưới dựa trên nhu cầu cây trồng thực tế, không theo thói quen',
    'bestPractices.farming.water.practice3': 'Phủ xung quanh cây để giảm bốc hơi',
    'bestPractices.farming.water.practice4': 'Bắt và lưu trữ nước mưa cho các giai đoạn khô hạn',
    'bestPractices.farming.water.practice5': 'Giám sát độ ẩm đất liên tục bằng cảm biến',
    
    'bestPractices.farming.pest': 'Kiểm soát sâu bệnh',
    'bestPractices.farming.pest.practice1': 'Triển khai chiến lược Quản lý dịch hại tổng hợp (IPM)',
    'bestPractices.farming.pest.practice2': 'Sử dụng kiểm soát sinh học (côn trùng có lợi, vi sinh vật) trước',
    'bestPractices.farming.pest.practice3': 'Thăm ruộng thường xuyên để phát hiện sâu bệnh sớm',
    'bestPractices.farming.pest.practice4': 'Luân canh để phá vỡ chu kỳ sâu bệnh',
    'bestPractices.farming.pest.practice5': 'Chọn giống kháng bệnh khi có sẵn',
    
    'bestPractices.farming.crop': 'Quản lý cây trồng',
    'bestPractices.farming.crop.practice1': 'Chọn giống phù hợp với khí hậu và đất của bạn',
    'bestPractices.farming.crop.practice2': 'Gieo trồng vào thời điểm tối ưu dựa trên thời tiết và điều kiện đất',
    'bestPractices.farming.crop.practice3': 'Duy trì khoảng cách phù hợp để lưu thông không khí và ánh sáng',
    'bestPractices.farming.crop.practice4': 'Giám sát các giai đoạn phát triển và điều chỉnh đầu vào phù hợp',
    'bestPractices.farming.crop.practice5': 'Thu hoạch ở độ chín đỉnh để có chất lượng và thời hạn sử dụng tối đa',
    
    'bestPractices.farming.record': 'Ghi chép hồ sơ',
    'bestPractices.farming.record.practice1': 'Ghi chép tất cả hoạt động gieo trồng, xử lý và thu hoạch',
    'bestPractices.farming.record.practice2': 'Theo dõi chi phí đầu vào và năng suất để phân tích khả năng sinh lời',
    'bestPractices.farming.record.practice3': 'Duy trì nhật ký bảo trì thiết bị',
    'bestPractices.farming.record.practice4': 'Ghi lại các mô hình thời tiết và tác động của chúng đến cây trồng',
    'bestPractices.farming.record.practice5': 'Sử dụng phần mềm quản lý trang trại để tập trung dữ liệu',
    
    // CTA Section
    'bestPractices.cta.title': 'Sẵn sàng triển khai những thực hành này?',
    'bestPractices.cta.description': 'Nền tảng thông minh của AgriBeacon giúp bạn theo dõi, đo lường và tối ưu hóa tất cả các thực hành tốt nhất này bằng dữ liệu thời gian thực và thông tin chi tiết có thể hành động.',
    'bestPractices.cta.button1': 'Khám phá giải pháp',
    'bestPractices.cta.button2': 'Nhận hướng dẫn chuyên gia',
    
    // Technology/Our Solutions Page
    'tech.title': 'Công nghệ của chúng tôi',
    'tech.subtitle': 'Phần cứng tiên tiến và phần mềm thông minh hoạt động hoàn hảo hài hòa',
    
    // Platform Features
    'tech.platform.cloud': 'Nền tảng đám mây',
    'tech.platform.cloud.desc': 'Cơ sở hạ tầng an toàn, có thể mở rộng',
    'tech.platform.security': 'Bảo mật dữ liệu',
    'tech.platform.security.desc': 'Mã hóa cấp độ ngân hàng',
    'tech.platform.network': 'Đa mạng',
    'tech.platform.network.desc': 'LoRaWAN, 4G, WiFi, Vệ tinh',
    'tech.platform.energy': 'Tiết kiệm năng lượng',
    'tech.platform.energy.desc': 'Năng lượng mặt trời + pin tuổi thọ cao',
    
    // Drones Tab
    'tech.drones.name': 'Máy bay không người lái tự động',
    'tech.drones.description': 'Trí tuệ không gian tiên tiến để giám sát và thu thập dữ liệu trang trại toàn diện',
    'tech.drones.spec1.label': 'Thời gian bay',
    'tech.drones.spec1.value': '45 phút',
    'tech.drones.spec2.label': 'Diện tích bao phủ',
    'tech.drones.spec2.value': '200 mẫu/chuyến bay',
    'tech.drones.spec3.label': 'Độ phân giải camera',
    'tech.drones.spec3.value': '4K đa phổ',
    'tech.drones.spec4.label': 'Xử lý AI',
    'tech.drones.spec4.value': 'Thời gian thực trên máy',
    'tech.drones.feature1': 'Lập kế hoạch và thực hiện bay tự động',
    'tech.drones.feature2': 'Hình ảnh đa phổ để phân tích sức khỏe cây trồng',
    'tech.drones.feature3': 'Phát hiện sâu bệnh thời gian thực',
    'tech.drones.feature4': 'Khả năng phun thuốc chính xác',
    'tech.drones.feature5': 'Lập bản đồ địa hình 3D',
    'tech.drones.feature6': 'Thiết kế chống thời tiết (IP54)',
    
    // IoT Sensors Tab
    'tech.sensors.name': 'Cảm biến IoT',
    'tech.sensors.description': 'Giám sát môi trường toàn diện với độ tin cậy cấp doanh nghiệp',
    'tech.sensors.spec1.label': 'Tuổi thọ pin',
    'tech.sensors.spec1.value': '3+ năm',
    'tech.sensors.spec2.label': 'Phạm vi',
    'tech.sensors.spec2.value': '10km LoRaWAN',
    'tech.sensors.spec3.label': 'Tần suất dữ liệu',
    'tech.sensors.spec3.value': 'Mỗi 15 phút',
    'tech.sensors.spec4.label': 'Cảm biến mỗi đơn vị',
    'tech.sensors.spec4.value': '8+ thông số',
    'tech.sensors.feature1': 'Giám sát độ ẩm đất, nhiệt độ và pH',
    'tech.sensors.feature2': 'Dữ liệu thời tiết (nhiệt độ, độ ẩm, mưa, gió)',
    'tech.sensors.feature3': 'Theo dõi cường độ ánh sáng và chỉ số UV',
    'tech.sensors.feature4': 'Đo chất lượng không khí và CO2',
    'tech.sensors.feature5': 'Năng lượng mặt trời với pin dự phòng',
    'tech.sensors.feature6': 'Chống nước và chống thời tiết (IP67)',
    
    // Robotics Tab
    'tech.robotics.name': 'Robot thông minh',
    'tech.robotics.description': 'Hệ thống robot tự động cho các nhiệm vụ canh tác chính xác và tự động hóa lao động',
    'tech.robotics.spec1.label': 'Thời gian hoạt động',
    'tech.robotics.spec1.value': '8-12 giờ',
    'tech.robotics.spec2.label': 'Độ chính xác',
    'tech.robotics.spec2.value': 'Độ chính xác ±2cm',
    'tech.robotics.spec3.label': 'Tải trọng',
    'tech.robotics.spec3.value': 'Sức chứa 50kg',
    'tech.robotics.spec4.label': 'Tốc độ',
    'tech.robotics.spec4.value': '0.5-2 m/s',
    'tech.robotics.feature1': 'Làm cỏ tự động với độ chính xác 99%',
    'tech.robotics.feature2': 'Trồng và gieo hạt chính xác',
    'tech.robotics.feature3': 'Khả năng thu hoạch có chọn lọc',
    'tech.robotics.feature4': 'Điều hướng qua GPS + tầm nhìn máy tính',
    'tech.robotics.feature5': 'Phát hiện và tránh vật cản',
    'tech.robotics.feature6': 'Sạc tự động và lập kế hoạch tuyến đường',
    
    // AI Analytics Tab
    'tech.ai.name': 'Phân tích AI',
    'tech.ai.description': 'Thông tin chi tiết được hỗ trợ bởi học máy và phân tích dự đoán để quản lý trang trại tối ưu',
    'tech.ai.spec1.label': 'Xử lý',
    'tech.ai.spec1.value': 'Đám mây + Biên',
    'tech.ai.spec2.label': 'Dự đoán',
    'tech.ai.spec2.value': 'Dự báo 7-30 ngày',
    'tech.ai.spec3.label': 'Độ chính xác',
    'tech.ai.spec3.value': 'Trung bình 92%+',
    'tech.ai.spec4.label': 'Điểm dữ liệu',
    'tech.ai.spec4.value': '1 triệu+/ngày',
    'tech.ai.feature1': 'Dự đoán và tối ưu hóa năng suất',
    'tech.ai.feature2': 'Hệ thống cảnh báo sớm dịch bệnh',
    'tech.ai.feature3': 'Đề xuất lịch trình tưới tiêu',
    'tech.ai.feature4': 'Tối ưu hóa thời điểm thu hoạch',
    'tech.ai.feature5': 'Lập kế hoạch phân bổ tài nguyên',
    'tech.ai.feature6': 'Phân tích xu hướng lịch sử và so sánh',
    
    'tech.keyFeatures': 'Tính năng chính',
    'tech.integration.title': 'Tích hợp liền mạch',
    'tech.integration.description': 'Tất cả công nghệ của chúng tôi hoạt động cùng nhau thông qua nền tảng AgriBeacon, cung cấp cái nhìn thống nhất về hoạt động trang trại của bạn với đồng bộ hóa dữ liệu thời gian thực và tự động hóa thông minh.',
  },
  ja: {
    'home.hero.badge': '精密農業テクノロジー',
    'home.hero.title1': '精密な信号。',
    'home.hero.title2': 'スマートセンシング。',
    'home.hero.title3': '持続可能な成長。',
    'home.hero.subtitle': 'インテリジェントなエンドツーエンドの農業技術ソリューションで農場を変革。土壌から収穫まで、すべての決定を最適化。',
    'home.hero.explore': 'ソリューションを探索',
    'home.hero.demo': 'デモをリクエスト',
    
    'home.vision.title': '私たちのビジョン',
    'home.vision.subtitle': '多年生植物農場向けのインテリジェントでエンドツーエンドの農業技術ソリューションの世界有数のプロバイダーになること — 経済的、生態学的、社会的に繁栄できるようにします。',
    'home.mission.title': '私たちのミッション',
    'home.mission.text1': '自律ドローン、ロボティクス、IoTセンサー、AI搭載分析を含むハードウェアとソフトウェアの統合エコシステムを通じて、農家と農業ビジネスに力を与え、土壌から収穫までのすべての決定を最適化します。',
    'home.mission.text2': '私たちのミッションは、精密性、自動化、洞察を通じて農業を変革し、人々と地球の両方に測定可能なインパクトをもたらすことです。',
    'home.stats.farms': '最適化された農場',
    'home.stats.data': '日次データポイント',
    'home.stats.yield': '収量増加',
    'home.stats.water': '節水',
    
    'home.solutions.title': 'インテリジェントソリューション',
    'home.solutions.subtitle': '最先端の農業技術の完全なエコシステム',
    'home.solutions.autonomous': '自律ドローン',
    'home.solutions.autonomous.desc': 'インテリジェントな空中監視とデータ収集',
    'home.solutions.robotics': 'スマートロボティクス',
    'home.solutions.robotics.desc': '自動化された農業オペレーションと精密タスク',
    'home.solutions.iot': 'IoTセンサー',
    'home.solutions.iot.desc': 'リアルタイム環境監視とアラート',
    'home.solutions.ai': 'AI分析',
    'home.solutions.ai.desc': '最適な意思決定のためのデータ駆動型洞察',
    'home.solutions.viewAll': 'すべてのソリューションを見る',
    
    'home.cta.title': '農場を変革する準備はできていますか？',
    'home.cta.subtitle': '収量を増加し、廃棄物を削減し、持続可能な未来を築くためにAgriBeaconを使用している数百の先見性のある農場に参加してください。',
    'home.cta.demo': 'デモをスケジュール',
    'home.cta.learn': '詳細を見る',
    
    // Navigation
    'nav.technology': '私たちのソリューション',
    'nav.resources': 'リソース',
    'nav.pricing': '料金',
    'nav.about': '会社概要',
    'nav.contact': 'お問い合わせ',
    'nav.login': 'ログイン',
    'nav.tryForFree': '無料で試す',
    'nav.contactSales': '営業に問い合わせ',
    
    // Technology menu
    'nav.technology.platform': 'プラットフォーム概要',
    'nav.technology.ai': 'AI分析',
    'nav.technology.connectivity': '接続性',
    'nav.technology.all': 'すべてのテクノロジー',
    
    // Resources menu
    'nav.resources.bestPractices': 'ベストプラクティス',
    
    // About menu
    'nav.about.aboutUs': '会社について',
    'nav.about.careers': '採用情報',
    'nav.about.contact': 'お問い合わせ',
    
    // Menu descriptions
    'nav.technology.platform.desc': '統合B2B農場管理',
    'nav.technology.ai.desc': 'ビジネス向け予測分析',
    'nav.technology.connectivity.desc': 'LoRaWAN & マルチネットワーク',
    'nav.technology.all.desc': '技術スタックを探索',
    'nav.resources.bestPractices.desc': '農業ガイド & ESG',
    'nav.about.aboutUs.desc': 'ミッション & ビジョン',
    'nav.about.careers.desc': 'チームに参加',
    'nav.about.contact.desc': 'お問い合わせ',
    'nav.pricing.desc': 'B2Bソリューション & パッケージ',
    
    // Footer
    'footer.company': '会社',
    'footer.solutions': 'ソリューション',
    'footer.technology': 'テクノロジー',
    'footer.resources': 'リソース',
    'footer.legal': '法的',
    'footer.copyright': '© 2024 AgriBeacon. 全著作権所有。',
    'footer.tagline': '精密な信号。スマートセンシング。持続可能な成長。インテリジェントな農業技術ソリューションで農家に力を与える。',
    'footer.quickLinks': 'クイックリンク',
    'footer.documentation': 'ドキュメント',
    'footer.support': 'サポート',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.builtFor': '持続可能な農業のために構築。',
    
    // About Page
    'about.title': 'AgriBeaconについて',
    'about.subtitle': 'インテリジェント技術で農業の未来を導く',
    'about.vision.title': '私たちのビジョン',
    'about.vision.text1': '多年生植物農場向けのインテリジェントでエンドツーエンドの農業技術ソリューションの世界有数のプロバイダーになること — 経済的、生態学的、社会的に繁栄できるようにします。',
    'about.vision.text2': '持続可能な成長、環境責任、長期的なコミュニティへの影響を支持する、回復力があり、データ駆動型の農業の未来を思い描いています — グローバルなESG価値観と完全に一致しています。',
    'about.mission.title': '私たちのミッション',
    'about.mission.text1': '自律ドローン、ロボティクス、IoTセンサー、AI搭載分析を含むハードウェアとソフトウェアの統合エコシステムを通じて、農家と農業ビジネスに力を与え、土壌から収穫までのすべての決定を最適化します。',
    'about.mission.text2': '私たちのミッションは、精密性、自動化、洞察を通じて農業を変革し、人々と地球の両方に測定可能なインパクトをもたらすことです。',
    'about.name.title': 'なぜ"AgriBeacon"？',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': '農業、私たちの焦点の基盤であり、すべての活動の中心です。',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': '前進の道を示す導きの光またはインテリジェント信号。',
    'about.name.together': '一緒に、この名前は複雑で進化する農業環境において、明確な方向性、リアルタイムの洞察、スマートな自動化を提供するという私たちのコミットメントを反映しています。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.precision': '精密性',
    'about.values.precision.desc': '最適な結果を得るために、データ駆動型の意思決定と正確な測定を信じています。',
    'about.values.innovation': 'イノベーション',
    'about.values.innovation.desc': '最先端技術と新しいアプローチで常に限界を押し広げています。',
    'about.values.partnership': 'パートナーシップ',
    'about.values.partnership.desc': '農家と手を取り合って実際の課題を理解し解決します。',
    'about.values.sustainability': '持続可能性',
    'about.values.sustainability.desc': '農場と地球の両方に何世代にもわたって利益をもたらすソリューションを構築しています。',
    'about.impact.title': '私たちのインパクト',
    'about.impact.farms': 'アクティブ農場',
    'about.impact.acres': '監視エーカー',
    'about.impact.yield': '平均収量増加',
    'about.impact.water': '節水',
    
    // Careers Page
    'careers.title': 'AgriBeacon採用情報',
    'careers.subtitle': '農業の未来を築く',
    'careers.description': '最先端のロボティクス、AI、IoT技術で農業を変革するミッションに参加してください。食料安全保障と持続可能性に真の影響を与えます。',
    'careers.why.title': 'なぜAgriBeacon？',
    'careers.why.subtitle': '私たちは単に技術を構築しているのではなく、東南アジア全体の農家の実際の問題を解決しています。',
    'careers.benefits.impact': '真のインパクト',
    'careers.benefits.impact.desc': 'あなたの仕事は、農家が収量を増やし、廃棄物を削減し、持続可能な運営を構築するのを直接支援します。',
    'careers.benefits.tech': '最先端技術',
    'careers.benefits.tech.desc': '挑戦的な実世界のドメインで、自律ドローン、ロボティクス、IoTセンサー、AI/MLを扱います。',
    'careers.benefits.growth': '成長と株式',
    'careers.benefits.growth.desc': '早期に参加し、私たちと一緒に成長し、株式プログラムを通じて私たちが構築しているものの一部を所有します。',
    'careers.positions.title': '募集ポジション',
    'careers.positions.subtitle': '違いを生み出したい才能ある人々を探しています。',
    'careers.position.robotics.title': 'ロボティクスエンジニア – 農業自動化',
    'careers.position.robotics.desc': '食料の栽培方法を変革する自律ロボットとドローンを構築します。農業をよりスマートに、より持続可能に、より効率的にするために私たちに参加してください。',
    'careers.position.location': 'ハノイ',
    'careers.position.type.fulltime': 'フルタイム',
    'careers.position.equity': '株式利用可能',
    'careers.position.onsite': 'オンサイト',
    'careers.position.viewDetails': '詳細を見る',
    'careers.noRole.title': 'あなたの役割が見つかりませんか？',
    'careers.noRole.description': '私たちは常に才能ある人々を探しています。農業技術とイノベーションに情熱を持っている場合は、お問い合わせください。',
    'careers.noRole.contact': 'お問い合わせ',
    
    // Contact Page
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '農場を変革する準備はできていますか？AgriBeaconがよりスマートな成長をサポートする方法について話し合いましょう。',
    'contact.form.title': 'デモをリクエスト',
    'contact.form.name': '氏名',
    'contact.form.name.placeholder': '山田太郎',
    'contact.form.email': 'メールアドレス',
    'contact.form.email.placeholder': 'yamada@example.com',
    'contact.form.phone': '電話番号',
    'contact.form.phone.placeholder': '+81 XXX XXXX XXXX',
    'contact.form.farmSize': '農場面積（エーカー）',
    'contact.form.farmSize.placeholder': '例：200',
    'contact.form.message': 'メッセージ',
    'contact.form.message.placeholder': 'あなたの農業ビジネスと達成したいことについて教えてください...',
    'contact.form.submit': 'メッセージを送信',
    'contact.form.success.title': 'メッセージが送信されました！',
    'contact.form.success.description': 'お問い合わせいただきありがとうございます。当社のチームが24時間以内にご連絡いたします。',
    'contact.info.email': 'メール',
    'contact.info.phone': '電話',
    'contact.info.location': '所在地',
    'contact.support.title': 'サポート時間',
    'contact.support.weekday': '月曜日 - 金曜日：8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': '土曜日：9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': '日曜日：休業',
    'contact.support.urgent': '緊急技術サポートについては、エンタープライズパートナー向けに24時間365日対応のホットラインがご利用いただけます。',
    
    // Contact Sales Dialog
    'contactSales.title': '営業へのお問い合わせ - B2Bソリューション',
    'contactSales.description': '農場とビジネスニーズについてお聞かせください。当社のチームが24時間以内にご連絡いたします。',
    'contactSales.companyName': '会社名/農場名',
    'contactSales.companyName.placeholder': 'ABC農業株式会社',
    'contactSales.contactName': '担当者名',
    'contactSales.contactName.placeholder': '山田太郎',
    'contactSales.email': 'ビジネスメール',
    'contactSales.email.placeholder': 'yamada@example.com',
    'contactSales.phone': '電話番号',
    'contactSales.phone.placeholder': '+81 XXX XXXX XXXX',
    'contactSales.farmSize': '総農場面積（エーカー）',
    'contactSales.farmSize.placeholder': '例：500',
    'contactSales.location': '農場の所在地',
    'contactSales.location.placeholder': '都道府県/地域',
    'contactSales.cropTypes': '主な作物種類',
    'contactSales.cropTypes.placeholder': '例：米、コーヒー、野菜',
    'contactSales.challenges': '現在の農業の課題',
    'contactSales.challenges.placeholder': '農業運営で直面している課題は何ですか？',
    'contactSales.needs': '具体的なニーズと関心のあるソリューション',
    'contactSales.needs.placeholder': '関心のあるソリューションについてお聞かせください（IoTセンサー、ドローン、ロボティクス、プラットフォームなど）',
    'contactSales.submit': 'お問い合わせを送信',
    'contactSales.success.title': 'メールクライアントを開いています',
    'contactSales.success.description': '事前入力された情報でメールクライアントが開きます。',
    
    // Solutions/Pricing Page
    'solutions.title': '完全なソリューション',
    'solutions.subtitle': '初日から農業運営を変革するために設計されたハードウェア + ソフトウェアパッケージ',
    'solutions.platform.title': 'AgriBeacon農場管理プラットフォーム',
    'solutions.platform.subtitle': 'すべてのパッケージに含まれるクラウドベースのSaaSプラットフォーム。どこからでも農場全体を監視、分析、最適化できます。',
    'solutions.platform.feature1': 'リアルタイム農場ダッシュボード',
    'solutions.platform.feature2': '予測分析と予測',
    'solutions.platform.feature3': '自動アラートと通知',
    'solutions.platform.feature4': '履歴データとトレンド分析',
    'solutions.platform.feature5': 'リソース最適化の推奨事項',
    'solutions.platform.feature6': 'マルチ農場管理',
    'solutions.platform.feature7': '統合用APIアクセス',
    'solutions.platform.feature8': 'モバイルとデスクトップアプリケーション',
    'solutions.badge.popular': '最も人気',
    'solutions.package.starter.name': 'スターターパッケージ',
    'solutions.package.starter.price': 'お問い合わせ',
    'solutions.package.starter.description': '精密農業の旅を始める中小規模農場に最適',
    'solutions.package.starter.feature1': '5つのIoT土壌センサー',
    'solutions.package.starter.feature2': 'リアルタイム監視ダッシュボード',
    'solutions.package.starter.feature3': '基本的な天気統合',
    'solutions.package.starter.feature4': 'モバイルアプリアクセス',
    'solutions.package.starter.feature5': 'メールサポート',
    'solutions.package.starter.feature6': '月次分析レポート',
    'solutions.package.professional.name': 'プロフェッショナルパッケージ',
    'solutions.package.professional.price': 'お問い合わせ',
    'solutions.package.professional.description': '運営を最適化する準備ができた真剣な農家のための完全なソリューション',
    'solutions.package.professional.feature1': '15のIoTマルチセンサーステーション',
    'solutions.package.professional.feature2': 'AIビジョン付き自律ドローン1台',
    'solutions.package.professional.feature3': '高度な分析と予測',
    'solutions.package.professional.feature4': '自動灌漑制御',
    'solutions.package.professional.feature5': '優先サポートとトレーニング',
    'solutions.package.professional.feature6': 'カスタム統合オプション',
    'solutions.package.professional.feature7': '週次最適化レポート',
    'solutions.package.enterprise.name': 'エンタープライズパッケージ',
    'solutions.package.enterprise.price': 'カスタム',
    'solutions.package.enterprise.description': '大規模農業運営のためのフルスケール展開',
    'solutions.package.enterprise.feature1': '無制限のセンサーネットワーク',
    'solutions.package.enterprise.feature2': '複数の自律ドローン',
    'solutions.package.enterprise.feature3': 'スマートロボットのフリート',
    'solutions.package.enterprise.feature4': '専用AI農場マネージャー',
    'solutions.package.enterprise.feature5': '24/7プレミアムサポート',
    'solutions.package.enterprise.feature6': 'オンサイトインストールとトレーニング',
    'solutions.package.enterprise.feature7': 'カスタムソフトウェア開発',
    'solutions.package.enterprise.feature8': 'リアルタイムコンサルタントアクセス',
    'solutions.cta.title': 'カスタムソリューションが必要ですか？',
    'solutions.cta.description': 'あらゆる規模の農場と協力して、特定のニーズを満たすカスタマイズされたソリューションを作成します。要件について話し合うために当社のチームにお問い合わせください。',
    'solutions.cta.button': '営業へのお問い合わせ',
    'solutions.button.tryFree': '無料でお試し',
    
    // Best Practices Page
    'bestPractices.badge': 'ナレッジハブ',
    'bestPractices.title': 'ベストプラクティス',
    'bestPractices.subtitle': '持続可能性、収益性、環境スチュワードシップのための現代的な農業戦略',
    
    // Tabs
    'bestPractices.tabs.circular': '循環型経済',
    'bestPractices.tabs.esg': 'ESGフレームワーク',
    'bestPractices.tabs.technology': 'テクノロジー',
    'bestPractices.tabs.farming': '農業実践',
    
    // Circular Economy Tab
    'bestPractices.circular.title': '現代農場のための循環型経済',
    'bestPractices.circular.description': '廃棄物がリソースになる閉ループシステムに農場を変革し、コストと環境への影響を削減しながら回復力を向上させます。',
    
    'bestPractices.circular.waste.title': '廃棄物からリソースへのシステム',
    'bestPractices.circular.waste.description': '堆肥化、バイオガス生産、有機肥料作成を通じて農業廃棄物を貴重なリソースに変換します。',
    'bestPractices.circular.waste.tip1': '有機廃棄物の農場内堆肥化システムを実装する',
    'bestPractices.circular.waste.tip2': '作物残渣をバイオエネルギーまたはバイオチャーに変換する',
    'bestPractices.circular.waste.tip3': '動物廃棄物をバイオガスと天然肥料に使用する',
    'bestPractices.circular.waste.tip4': '閉ループ栄養サイクルを確立する',
    
    'bestPractices.circular.water.title': '水のリサイクルと再利用',
    'bestPractices.circular.water.description': 'リサイクル、雨水収集、精密灌漑システムを通じて水の効率を最大化します。',
    'bestPractices.circular.water.tip1': '雨水収集および貯蔵システムを設置する',
    'bestPractices.circular.water.tip2': '水分センサー付き点滴灌漑を実装する',
    'bestPractices.circular.water.tip3': '処理済み廃水を非食用作物に再利用する',
    'bestPractices.circular.water.tip4': '水の蒸発損失を監視し最小化する',
    
    'bestPractices.circular.regenerative.title': '再生農業',
    'bestPractices.circular.regenerative.description': '食料を生産しながら土壌の健康と生物多様性を構築し、自己持続型の生態系を作成します。',
    'bestPractices.circular.regenerative.tip1': '輪作とカバークロッピングを実践する',
    'bestPractices.circular.regenerative.tip2': '不耕起法で土壌の乱れを最小限に抑える',
    'bestPractices.circular.regenerative.tip3': '自然施肥のために家畜を統合する',
    'bestPractices.circular.regenerative.tip4': '生物多様性回廊を保存し強化する',
    
    'bestPractices.circular.sharing.title': 'リソースシェアリングエコノミー',
    'bestPractices.circular.sharing.description': '協力的な農業モデルを通じて設備の利用を最適化し、コストを削減します。',
    'bestPractices.circular.sharing.tip1': '近隣の農場と高価な機械を共有する',
    'bestPractices.circular.sharing.tip2': '協同購入プログラムに参加する',
    'bestPractices.circular.sharing.tip3': '地域で知識とベストプラクティスを交換する',
    'bestPractices.circular.sharing.tip4': '大量再生可能エネルギー投資のためにリソースをプールする',
    
    // ESG Framework Tab
    'bestPractices.esg.title': '農業のためのESGフレームワーク',
    'bestPractices.esg.description': '環境、社会、ガバナンスの原則を採用して、現代の投資家と消費者の期待に応える持続可能で責任ある農場を構築します。',
    
    'bestPractices.esg.environmental': '環境',
    'bestPractices.esg.env.carbon.title': '炭素隔離',
    'bestPractices.esg.env.carbon.description': '土壌管理と植林を通じて大気中のCO2を捕獲し貯蔵する',
    'bestPractices.esg.env.carbon.metrics': '目標：カーボンニュートラルまたはカーボンネガティブ運営',
    
    'bestPractices.esg.env.biodiversity.title': '生物多様性保護',
    'bestPractices.esg.env.biodiversity.description': '在来種を保存し、野生動物の生息地を作り、生態学的バランスを維持する',
    'bestPractices.esg.env.biodiversity.metrics': '測定：種の多様性指数と生息地面積',
    
    'bestPractices.esg.env.energy.title': 'クリーンエネルギー移行',
    'bestPractices.esg.env.energy.description': '太陽光、風力、バイオガスを採用して農場運営を持続可能に行う',
    'bestPractices.esg.env.energy.metrics': '目標：2030年までに80%以上の再生可能エネルギー',
    
    'bestPractices.esg.env.pollution.title': '汚染防止',
    'bestPractices.esg.env.pollution.description': '化学物質の流出を排除し、農薬使用を削減し、プラスチック廃棄物を最小化する',
    'bestPractices.esg.env.pollution.metrics': '追跡：水質と化学物質使用削減',
    
    'bestPractices.esg.social': '社会',
    'bestPractices.esg.social.labor.title': '公正な労働慣行',
    'bestPractices.esg.social.labor.description': '安全な労働条件、公正な賃金、労働者の福祉を確保する',
    'bestPractices.esg.social.labor.metrics': '認証：フェアトレードまたは同等の基準',
    
    'bestPractices.esg.social.community.title': 'コミュニティエンゲージメント',
    'bestPractices.esg.social.community.description': '地域社会をサポートし、雇用を創出し、地域開発に貢献する',
    'bestPractices.esg.social.community.metrics': '測定：地域雇用率とコミュニティ投資',
    
    'bestPractices.esg.social.knowledge.title': '知識移転',
    'bestPractices.esg.social.knowledge.description': '次世代の農家を訓練し、持続可能な慣行を共有する',
    'bestPractices.esg.social.knowledge.metrics': '目標：年次トレーニングプログラムと見習い',
    
    'bestPractices.esg.social.food.title': '食料安全保障',
    'bestPractices.esg.social.food.description': '地域および地方の食料の入手可能性とアクセシビリティに貢献する',
    'bestPractices.esg.social.food.metrics': '追跡：生産量と流通範囲',
    
    'bestPractices.esg.governance': 'ガバナンス',
    'bestPractices.esg.gov.reporting.title': '透明な報告',
    'bestPractices.esg.gov.reporting.description': '持続可能性報告書を公開し、環境影響データを共有する',
    'bestPractices.esg.gov.reporting.metrics': '年次ESG開示と第三者監査',
    
    'bestPractices.esg.gov.supply.title': '倫理的なサプライチェーン',
    'bestPractices.esg.gov.supply.description': '責任あるサプライヤーと提携し、トレーサビリティを確保する',
    'bestPractices.esg.gov.supply.metrics': 'サプライヤーのコンプライアンス検証100%',
    
    'bestPractices.esg.gov.data.title': 'データ駆動型意思決定',
    'bestPractices.esg.gov.data.description': '分析と監視を使用して持続可能性の改善を導く',
    'bestPractices.esg.gov.data.metrics': 'リアルタイムダッシュボードと四半期レビュー',
    
    'bestPractices.esg.gov.stakeholder.title': 'ステークホルダーエンゲージメント',
    'bestPractices.esg.gov.stakeholder.description': '農家、投資家、コミュニティを意思決定に関与させる',
    'bestPractices.esg.gov.stakeholder.metrics': '定期的なステークホルダー協議とフィードバックループ',
    
    // Technology Tab
    'bestPractices.tech.title': 'テクノロジーのベストプラクティス',
    'bestPractices.tech.description': '最先端の農業技術を活用して運営を最適化し、廃棄物を削減し、データ駆動型の意思決定を行います。',
    
    'bestPractices.tech.precision.title': '精密農業',
    'bestPractices.tech.precision.description': 'データと技術を使用して投入を最適化し、収量を最大化する',
    'bestPractices.tech.precision.impl1': '精密な植付けと散布のためのGPS誘導機器',
    'bestPractices.tech.precision.impl2': '肥料散布のための可変速度技術（VRT）',
    'bestPractices.tech.precision.impl3': '高低パフォーマンスゾーンを特定するための収量マッピング',
    'bestPractices.tech.precision.impl4': '対象を絞った改良のための土壌サンプリングと分析',
    
    'bestPractices.tech.iot.title': 'IoTセンサーネットワーク',
    'bestPractices.tech.iot.description': 'リアルタイム農場監視のために接続されたセンサーを展開する',
    'bestPractices.tech.iot.impl1': '灌漑最適化のための土壌水分センサー',
    'bestPractices.tech.iot.impl2': '微気候追跡のための気象観測所',
    'bestPractices.tech.iot.impl3': '健康と行動のための家畜監視',
    'bestPractices.tech.iot.impl4': '予測メンテナンスのための機器センサー',
    
    'bestPractices.tech.renewable.title': '再生可能エネルギー統合',
    'bestPractices.tech.renewable.description': 'クリーンエネルギー源を活用して運営を動かす',
    'bestPractices.tech.renewable.impl1': '納屋の屋根と未使用地にソーラーパネル',
    'bestPractices.tech.renewable.impl2': '適切な場所に風力タービン',
    'bestPractices.tech.renewable.impl3': '廃棄物からエネルギーへの変換のためのバイオガス消化装置',
    'bestPractices.tech.renewable.impl4': '24/7利用可能のためのエネルギー貯蔵システム',
    
    'bestPractices.tech.ai.title': 'データ分析とAI',
    'bestPractices.tech.ai.description': '予測洞察のために人工知能を活用する',
    'bestPractices.tech.ai.impl1': '作物病害予測と早期検出',
    'bestPractices.tech.ai.impl2': '過去のデータと天気データに基づく収量予測',
    'bestPractices.tech.ai.impl3': '最適な販売時期のための市場価格予測',
    'bestPractices.tech.ai.impl4': '自動化された意思決定支援システム',
    
    // Farming Practices Tab
    'bestPractices.farming.title': 'コア農業ベストプラクティス',
    'bestPractices.farming.description': '成功した持続可能な農業運営の基盤を形成する、時代を超えた科学的裏付けのある農業実践。',
    
    'bestPractices.farming.soil': '土壌の健康',
    'bestPractices.farming.soil.practice1': '栄養レベルとpHについて定期的に（少なくとも年1回）土壌を検査する',
    'bestPractices.farming.soil.practice2': '栄養枯渇を防ぐために輪作を実践する',
    'bestPractices.farming.soil.practice3': '侵食を防ぎ有機物を追加するためにカバークロップを使用する',
    'bestPractices.farming.soil.practice4': '合成肥料の代わりに堆肥と有機改良材を施用する',
    'bestPractices.farming.soil.practice5': '土壌構造と微生物を保存するために耕起を最小限に抑える',
    
    'bestPractices.farming.water': '水管理',
    'bestPractices.farming.water.practice1': '効率のために点滴またはマイクロスプリンクラー灌漑を設置する',
    'bestPractices.farming.water.practice2': 'ルーチンではなく実際の作物のニーズに基づいて灌漑をスケジュールする',
    'bestPractices.farming.water.practice3': '蒸発を減らすために植物の周りにマルチを敷く',
    'bestPractices.farming.water.practice4': '乾季のために雨水を捕獲して貯蔵する',
    'bestPractices.farming.water.practice5': 'センサーで土壌水分を継続的に監視する',
    
    'bestPractices.farming.pest': '害虫と病気の管理',
    'bestPractices.farming.pest.practice1': '総合的害虫管理（IPM）戦略を実装する',
    'bestPractices.farming.pest.practice2': '生物学的制御（有益な昆虫、微生物）を最初に使用する',
    'bestPractices.farming.pest.practice3': '早期害虫検出のために定期的に圃場を調査する',
    'bestPractices.farming.pest.practice4': '害虫と病気のサイクルを断つために作物を輪作する',
    'bestPractices.farming.pest.practice5': '利用可能な場合は耐病性品種を選択する',
    
    'bestPractices.farming.crop': '作物管理',
    'bestPractices.farming.crop.practice1': '気候と土壌に適した品種を選択する',
    'bestPractices.farming.crop.practice2': '天気と土壌条件に基づいて最適な時期に植える',
    'bestPractices.farming.crop.practice3': '空気循環と光のために適切な間隔を維持する',
    'bestPractices.farming.crop.practice4': '成長段階を監視し、それに応じて投入を調整する',
    'bestPractices.farming.crop.practice5': '最大の品質と貯蔵寿命のためにピーク成熟期に収穫する',
    
    'bestPractices.farming.record': '記録管理',
    'bestPractices.farming.record.practice1': 'すべての植付け、処理、収穫活動を記録する',
    'bestPractices.farming.record.practice2': '収益性分析のために投入コストと収量を追跡する',
    'bestPractices.farming.record.practice3': '機器メンテナンスログを維持する',
    'bestPractices.farming.record.practice4': '天気パターンと作物への影響を記録する',
    'bestPractices.farming.record.practice5': '一元化されたデータのために農場管理ソフトウェアを使用する',
    
    // CTA Section
    'bestPractices.cta.title': 'これらの実践を実装する準備はできていますか？',
    'bestPractices.cta.description': 'AgriBeaconのインテリジェントプラットフォームは、リアルタイムデータと実用的な洞察で、これらすべてのベストプラクティスを追跡、測定、最適化するのに役立ちます。',
    'bestPractices.cta.button1': 'ソリューションを探る',
    'bestPractices.cta.button2': '専門家のガイダンスを受ける',
    
    // Technology/Our Solutions Page
    'tech.title': '私たちのテクノロジー',
    'tech.subtitle': '最先端のハードウェアとインテリジェントなソフトウェアが完璧に調和して動作',
    
    // Platform Features
    'tech.platform.cloud': 'クラウドプラットフォーム',
    'tech.platform.cloud.desc': '安全でスケーラブルなインフラストラクチャ',
    'tech.platform.security': 'データセキュリティ',
    'tech.platform.security.desc': '銀行レベルの暗号化',
    'tech.platform.network': 'マルチネットワーク',
    'tech.platform.network.desc': 'LoRaWAN、4G、WiFi、衛星',
    'tech.platform.energy': 'エネルギー効率',
    'tech.platform.energy.desc': 'ソーラー＋長寿命バッテリー',
    
    // Drones Tab
    'tech.drones.name': '自律ドローン',
    'tech.drones.description': '包括的な農場監視とデータ収集のための高度な空中インテリジェンス',
    'tech.drones.spec1.label': '飛行時間',
    'tech.drones.spec1.value': '45分',
    'tech.drones.spec2.label': 'カバレッジエリア',
    'tech.drones.spec2.value': '200エーカー/飛行',
    'tech.drones.spec3.label': 'カメラ解像度',
    'tech.drones.spec3.value': '4Kマルチスペクトル',
    'tech.drones.spec4.label': 'AI処理',
    'tech.drones.spec4.value': 'リアルタイムオンボード',
    'tech.drones.feature1': '自律的な飛行計画と実行',
    'tech.drones.feature2': '作物の健康分析のためのマルチスペクトル画像',
    'tech.drones.feature3': 'リアルタイムの害虫と病気の検出',
    'tech.drones.feature4': '精密散布機能',
    'tech.drones.feature5': '3D地形マッピング',
    'tech.drones.feature6': '耐候性設計（IP54）',
    
    // IoT Sensors Tab
    'tech.sensors.name': 'IoTセンサー',
    'tech.sensors.description': 'エンタープライズグレードの信頼性を備えた包括的な環境監視',
    'tech.sensors.spec1.label': 'バッテリー寿命',
    'tech.sensors.spec1.value': '3年以上',
    'tech.sensors.spec2.label': '範囲',
    'tech.sensors.spec2.value': '10km LoRaWAN',
    'tech.sensors.spec3.label': 'データ頻度',
    'tech.sensors.spec3.value': '15分ごと',
    'tech.sensors.spec4.label': 'ユニットあたりのセンサー',
    'tech.sensors.spec4.value': '8パラメータ以上',
    'tech.sensors.feature1': '土壌水分、温度、pH監視',
    'tech.sensors.feature2': '気象データ（温度、湿度、降雨量、風）',
    'tech.sensors.feature3': '光強度とUVインデックスの追跡',
    'tech.sensors.feature4': '空気品質とCO2測定',
    'tech.sensors.feature5': 'バックアップバッテリー付きソーラー電源',
    'tech.sensors.feature6': '防水・耐候性（IP67）',
    
    // Robotics Tab
    'tech.robotics.name': 'スマートロボティクス',
    'tech.robotics.description': '精密農業タスクと労働自動化のための自律ロボットシステム',
    'tech.robotics.spec1.label': '動作時間',
    'tech.robotics.spec1.value': '8〜12時間',
    'tech.robotics.spec2.label': '精度',
    'tech.robotics.spec2.value': '±2cm精度',
    'tech.robotics.spec3.label': 'ペイロード',
    'tech.robotics.spec3.value': '50kg容量',
    'tech.robotics.spec4.label': '速度',
    'tech.robotics.spec4.value': '0.5〜2 m/s',
    'tech.robotics.feature1': '99%の精度での自動除草',
    'tech.robotics.feature2': '精密な植付けと播種',
    'tech.robotics.feature3': '選択的収穫機能',
    'tech.robotics.feature4': 'GPS +コンピュータビジョンによるナビゲーション',
    'tech.robotics.feature5': '障害物検出と回避',
    'tech.robotics.feature6': '自動充電とルート計画',
    
    // AI Analytics Tab
    'tech.ai.name': 'AI分析',
    'tech.ai.description': '最適な農場管理のための機械学習による洞察と予測分析',
    'tech.ai.spec1.label': '処理',
    'tech.ai.spec1.value': 'クラウド + エッジ',
    'tech.ai.spec2.label': '予測',
    'tech.ai.spec2.value': '7〜30日予測',
    'tech.ai.spec3.label': '精度',
    'tech.ai.spec3.value': '平均92%以上',
    'tech.ai.spec4.label': 'データポイント',
    'tech.ai.spec4.value': '1日100万以上',
    'tech.ai.feature1': '収量予測と最適化',
    'tech.ai.feature2': '病気発生の早期警告システム',
    'tech.ai.feature3': '灌漑スケジュールの推奨',
    'tech.ai.feature4': '収穫タイミングの最適化',
    'tech.ai.feature5': 'リソース配分計画',
    'tech.ai.feature6': '過去のトレンド分析とベンチマーク',
    
    'tech.keyFeatures': '主な機能',
    'tech.integration.title': 'シームレスな統合',
    'tech.integration.description': 'すべてのテクノロジーはAgriBeaconプラットフォームを通じて連携し、リアルタイムのデータ同期とインテリジェントな自動化により、農場運営の統一されたビューを提供します。',
  },
};

export const SimpleLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'vi', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <SimpleLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </SimpleLanguageContext.Provider>
  );
};

export const useSimpleLanguage = () => {
  const context = useContext(SimpleLanguageContext);
  if (context === undefined) {
    throw new Error('useSimpleLanguage must be used within a SimpleLanguageProvider');
  }
  return context;
};
