import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'vi' | 'ja';

interface SimpleLanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const SimpleLanguageContext = createContext<SimpleLanguageContextType | undefined>(undefined);

// Simple translations for Home page only
const translations = {
  en: {
    'home.hero.badge': 'Precision Agriculture Technology',
    'home.hero.title1': 'Precise signals.',
    'home.hero.title2': 'Smarter sensing.',
    'home.hero.title3': 'Sustainable growth.',
    'home.hero.subtitle': 'Transform your farm with intelligent, end-to-end agricultural technology solutions. Optimize every decision from soil to harvest.',
    'home.hero.explore': 'Explore Solutions',
    'home.hero.demo': 'Request Demo',
    
    'home.vision.title': 'Our Vision',
    'home.vision.subtitle': 'To become the world\'s leading provider of intelligent, end-to-end agricultural technology solutions for perennial plant farms — enabling them to thrive economically, ecologically, and socially.',
    'home.mission.title': 'Our Mission',
    'home.mission.text1': 'We empower farmers and agricultural businesses through a unified ecosystem of hardware and software — including autonomous drones, robotics, IoT sensors, and AI-powered analytics — to optimize every decision from soil to harvest.',
    'home.mission.text2': 'Our mission is to transform agriculture through precision, automation, and insight, delivering measurable impact to both people and planet.',
    'home.stats.farms': 'Farms Optimized',
    'home.stats.data': 'Data Points Daily',
    'home.stats.yield': 'Yield Increase',
    'home.stats.water': 'Water Saved',
    
    'home.solutions.title': 'Intelligent Solutions',
    'home.solutions.subtitle': 'A complete ecosystem of cutting-edge agricultural technology',
    'home.solutions.autonomous': 'Autonomous Drones',
    'home.solutions.autonomous.desc': 'Intelligent aerial monitoring and data collection',
    'home.solutions.robotics': 'Smart Robotics',
    'home.solutions.robotics.desc': 'Automated farming operations and precision tasks',
    'home.solutions.iot': 'IoT Sensors',
    'home.solutions.iot.desc': 'Real-time environmental monitoring and alerts',
    'home.solutions.ai': 'AI Analytics',
    'home.solutions.ai.desc': 'Data-driven insights for optimal decision making',
    'home.solutions.viewAll': 'View All Solutions',
    
    'home.cta.title': 'Ready to Transform Your Farm?',
    'home.cta.subtitle': 'Join hundreds of forward-thinking farms using AgriBeacon to increase yields, reduce waste, and build a sustainable future.',
    'home.cta.demo': 'Schedule a Demo',
    'home.cta.learn': 'Learn More',
    
    // Navigation
    'nav.technology': 'Technology',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact Us',
    'nav.login': 'Login',
    'nav.tryForFree': 'Try for FREE',
    'nav.contactSales': 'Contact Sales',
    
    // Technology menu
    'nav.technology.platform': 'Platform Overview',
    'nav.technology.ai': 'AI Analytics',
    'nav.technology.connectivity': 'Connectivity',
    'nav.technology.all': 'All Technology',
    
    // Resources menu
    'nav.resources.bestPractices': 'Best Practices',
    
    // About menu
    'nav.about.aboutUs': 'About Us',
    'nav.about.careers': 'Careers',
    'nav.about.contact': 'Contact',
    
    // Menu descriptions
    'nav.technology.platform.desc': 'Integrated B2B farm management',
    'nav.technology.ai.desc': 'Predictive insights for businesses',
    'nav.technology.connectivity.desc': 'LoRaWAN & Multi-network',
    'nav.technology.all.desc': 'Explore our tech stack',
    'nav.resources.bestPractices.desc': 'Farming guides & ESG',
    'nav.about.aboutUs.desc': 'Our mission & vision',
    'nav.about.careers.desc': 'Join our team',
    'nav.about.contact.desc': 'Get in touch',
    'nav.pricing.desc': 'B2B solutions & packages',
    
    // Footer
    'footer.company': 'Company',
    'footer.solutions': 'Solutions',
    'footer.technology': 'Technology',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2024 AgriBeacon. All rights reserved.',
    'footer.tagline': 'Precise signals. Smarter sensing. Sustainable growth. Empowering farmers with intelligent agricultural technology solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.documentation': 'Documentation',
    'footer.support': 'Support',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.builtFor': 'Built for sustainable agriculture.',
    
    // About Page
    'about.title': 'About AgriBeacon',
    'about.subtitle': 'Guiding the future of agriculture with intelligent technology',
    'about.vision.title': 'Our Vision',
    'about.vision.text1': 'To become the world\'s leading provider of intelligent, end-to-end agricultural technology solutions for perennial plant farms — enabling them to thrive economically, ecologically, and socially.',
    'about.vision.text2': 'We envision a resilient, data-driven farming future that champions sustainable growth, environmental responsibility, and long-term community impact — fully aligned with global ESG values.',
    'about.mission.title': 'Our Mission',
    'about.mission.text1': 'We empower farmers and agricultural businesses through a unified ecosystem of hardware and software — including autonomous drones, robotics, IoT sensors, and AI-powered analytics — to optimize every decision from soil to harvest.',
    'about.mission.text2': 'Our mission is to transform agriculture through precision, automation, and insight, delivering measurable impact to both people and planet.',
    'about.name.title': 'Why "AgriBeacon"?',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': 'Agriculture, the foundation of our focus and the heart of everything we do.',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': 'A guiding light or intelligent signal that shows the way forward.',
    'about.name.together': 'Together, the name reflects our commitment to providing clear direction, real-time insight, and smart automation in a complex and evolving farming environment.',
    'about.values.title': 'Our Core Values',
    'about.values.precision': 'Precision',
    'about.values.precision.desc': 'We believe in data-driven decisions and accurate measurements for optimal results.',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Constantly pushing boundaries with cutting-edge technology and fresh approaches.',
    'about.values.partnership': 'Partnership',
    'about.values.partnership.desc': 'Working hand-in-hand with farmers to understand and solve real challenges.',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability.desc': 'Building solutions that benefit both farms and the planet for generations to come.',
    'about.impact.title': 'Our Impact',
    'about.impact.farms': 'Active Farms',
    'about.impact.acres': 'Acres Monitored',
    'about.impact.yield': 'Avg. Yield Increase',
    'about.impact.water': 'Water Savings',
    
    // Careers Page
    'careers.title': 'AgriBeacon Careers',
    'careers.subtitle': 'Build the Future of Agriculture',
    'careers.description': 'Join our mission to transform farming with cutting-edge robotics, AI, and IoT technology. Make a real impact on food security and sustainability.',
    'careers.why.title': 'Why AgriBeacon?',
    'careers.why.subtitle': 'We\'re not just building technology—we\'re solving real problems for farmers across Southeast Asia.',
    'careers.benefits.impact': 'Real Impact',
    'careers.benefits.impact.desc': 'Your work directly helps farmers increase yields, reduce waste, and build sustainable operations.',
    'careers.benefits.tech': 'Cutting-Edge Tech',
    'careers.benefits.tech.desc': 'Work with autonomous drones, robotics, IoT sensors, and AI/ML in a challenging real-world domain.',
    'careers.benefits.growth': 'Growth & Equity',
    'careers.benefits.growth.desc': 'Join early, grow with us, and own part of what we\'re building through our equity program.',
    'careers.positions.title': 'Open Positions',
    'careers.positions.subtitle': 'We\'re looking for talented people who want to make a difference.',
    'careers.position.robotics.title': 'Robotics Engineer – Agricultural Automation',
    'careers.position.robotics.desc': 'Build autonomous robots and drones that are transforming how we grow food. Join us in making agriculture smarter, more sustainable, and more efficient.',
    'careers.position.location': 'Ha Noi',
    'careers.position.type.fulltime': 'Full-time',
    'careers.position.equity': 'Equity Available',
    'careers.position.onsite': 'Onsite',
    'careers.position.viewDetails': 'View Details',
    'careers.noRole.title': 'Don\'t See Your Role?',
    'careers.noRole.description': 'We\'re always looking for talented people. If you\'re passionate about agtech and innovation, reach out to us.',
    'careers.noRole.contact': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Ready to transform your farm? Let\'s discuss how AgriBeacon can help you grow smarter.',
    'contact.form.title': 'Request a Demo',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'John Doe',
    'contact.form.email': 'Email Address',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.phone': 'Phone Number',
    'contact.form.phone.placeholder': '+1 XXX XXX XXXX',
    'contact.form.farmSize': 'Farm Size (acres)',
    'contact.form.farmSize.placeholder': 'e.g., 200',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your farm business and what you\'re looking to achieve...',
    'contact.form.submit': 'Send Message',
    'contact.form.success.title': 'Message Sent!',
    'contact.form.success.description': 'Thank you for your interest. Our team will contact you within 24 hours.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.support.title': 'Support Hours',
    'contact.support.weekday': 'Monday - Friday: 8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': 'Saturday: 9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': 'Sunday: Closed',
    'contact.support.urgent': 'For urgent technical support, our 24/7 hotline is available for Enterprise partners.',
    
    // Contact Sales Dialog
    'contactSales.title': 'Contact Sales - B2B Solutions',
    'contactSales.description': 'Tell us about your farm and business needs, and our team will get back to you within 24 hours.',
    'contactSales.companyName': 'Company/Farm Name',
    'contactSales.companyName.placeholder': 'ABC Agricultural Co.',
    'contactSales.contactName': 'Contact Person',
    'contactSales.contactName.placeholder': 'John Doe',
    'contactSales.email': 'Business Email',
    'contactSales.email.placeholder': 'john@example.com',
    'contactSales.phone': 'Phone Number',
    'contactSales.phone.placeholder': '+1 XXX XXX XXXX',
    'contactSales.farmSize': 'Total Farm Size (acres)',
    'contactSales.farmSize.placeholder': 'e.g., 500',
    'contactSales.location': 'Farm Location',
    'contactSales.location.placeholder': 'Province/Region',
    'contactSales.cropTypes': 'Main Crop Types',
    'contactSales.cropTypes.placeholder': 'e.g., Rice, Coffee, Vegetables',
    'contactSales.challenges': 'Current Farming Challenges',
    'contactSales.challenges.placeholder': 'What challenges are you facing in your farming operations?',
    'contactSales.needs': 'Specific Needs & Solutions of Interest',
    'contactSales.needs.placeholder': 'Tell us about the solutions you\'re interested in (IoT sensors, drones, robotics, platform, etc.)',
    'contactSales.submit': 'Submit Inquiry',
    'contactSales.success.title': 'Opening Email Client',
    'contactSales.success.description': 'Your email client will open with the pre-filled information.',
  },
  vi: {
    'home.hero.badge': 'Công nghệ nông nghiệp chính xác',
    'home.hero.title1': 'Tín hiệu chính xác.',
    'home.hero.title2': 'Cảm biến thông minh.',
    'home.hero.title3': 'Tăng trưởng bền vững.',
    'home.hero.subtitle': 'Chuyển đổi trang trại của bạn với các giải pháp công nghệ nông nghiệp thông minh, toàn diện. Tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'home.hero.explore': 'Khám phá giải pháp',
    'home.hero.demo': 'Yêu cầu demo',
    
    'home.vision.title': 'Tầm nhìn của chúng tôi',
    'home.vision.subtitle': 'Trở thành nhà cung cấp hàng đầu thế giới về các giải pháp công nghệ nông nghiệp thông minh, toàn diện cho các trang trại cây lâu năm — giúp họ phát triển mạnh về kinh tế, sinh thái và xã hội.',
    'home.mission.title': 'Sứ mệnh của chúng tôi',
    'home.mission.text1': 'Chúng tôi trao quyền cho nông dân và doanh nghiệp nông nghiệp thông qua hệ sinh thái thống nhất của phần cứng và phần mềm — bao gồm máy bay không người lái tự động, robot, cảm biến IoT và phân tích AI — để tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'home.mission.text2': 'Sứ mệnh của chúng tôi là chuyển đổi nông nghiệp thông qua độ chính xác, tự động hóa và thông tin chi tiết, mang lại tác động có thể đo lường được cho cả con người và hành tinh.',
    'home.stats.farms': 'Trang trại được tối ưu',
    'home.stats.data': 'Điểm dữ liệu hàng ngày',
    'home.stats.yield': 'Tăng năng suất',
    'home.stats.water': 'Tiết kiệm nước',
    
    'home.solutions.title': 'Giải pháp thông minh',
    'home.solutions.subtitle': 'Hệ sinh thái hoàn chỉnh của công nghệ nông nghiệp tiên tiến',
    'home.solutions.autonomous': 'Máy bay không người lái tự động',
    'home.solutions.autonomous.desc': 'Giám sát trên không thông minh và thu thập dữ liệu',
    'home.solutions.robotics': 'Robot thông minh',
    'home.solutions.robotics.desc': 'Hoạt động nông nghiệp tự động và nhiệm vụ chính xác',
    'home.solutions.iot': 'Cảm biến IoT',
    'home.solutions.iot.desc': 'Giám sát môi trường thời gian thực và cảnh báo',
    'home.solutions.ai': 'Phân tích AI',
    'home.solutions.ai.desc': 'Thông tin chi tiết dựa trên dữ liệu để ra quyết định tối ưu',
    'home.solutions.viewAll': 'Xem tất cả giải pháp',
    
    'home.cta.title': 'Sẵn sàng chuyển đổi trang trại của bạn?',
    'home.cta.subtitle': 'Tham gia cùng hàng trăm trang trại có tầm nhìn xa sử dụng AgriBeacon để tăng năng suất, giảm lãng phí và xây dựng tương lai bền vững.',
    'home.cta.demo': 'Đặt lịch demo',
    'home.cta.learn': 'Tìm hiểu thêm',
    
    // Navigation
    'nav.technology': 'Công nghệ',
    'nav.resources': 'Tài nguyên',
    'nav.pricing': 'Bảng giá',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'nav.tryForFree': 'Dùng thử MIỄN PHÍ',
    'nav.contactSales': 'Liên hệ bán hàng',
    
    // Technology menu
    'nav.technology.platform': 'Tổng quan nền tảng',
    'nav.technology.ai': 'Phân tích AI',
    'nav.technology.connectivity': 'Kết nối',
    'nav.technology.all': 'Tất cả công nghệ',
    
    // Resources menu
    'nav.resources.bestPractices': 'Thực hành tốt nhất',
    
    // About menu
    'nav.about.aboutUs': 'Về chúng tôi',
    'nav.about.careers': 'Tuyển dụng',
    'nav.about.contact': 'Liên hệ',
    
    // Menu descriptions
    'nav.technology.platform.desc': 'Quản lý trang trại B2B tích hợp',
    'nav.technology.ai.desc': 'Phân tích dự đoán cho doanh nghiệp',
    'nav.technology.connectivity.desc': 'LoRaWAN & Đa mạng',
    'nav.technology.all.desc': 'Khám phá ngăn xếp công nghệ',
    'nav.resources.bestPractices.desc': 'Hướng dẫn nông nghiệp & ESG',
    'nav.about.aboutUs.desc': 'Sứ mệnh & tầm nhìn',
    'nav.about.careers.desc': 'Tham gia đội ngũ',
    'nav.about.contact.desc': 'Liên hệ với chúng tôi',
    'nav.pricing.desc': 'Giải pháp & gói B2B',
    
    // Footer
    'footer.company': 'Công ty',
    'footer.solutions': 'Giải pháp',
    'footer.technology': 'Công nghệ',
    'footer.resources': 'Tài nguyên',
    'footer.legal': 'Pháp lý',
    'footer.copyright': '© 2024 AgriBeacon. Tất cả quyền được bảo lưu.',
    'footer.tagline': 'Tín hiệu chính xác. Cảm biến thông minh. Tăng trưởng bền vững. Trao quyền cho nông dân với các giải pháp công nghệ nông nghiệp thông minh.',
    'footer.quickLinks': 'Liên kết nhanh',
    'footer.documentation': 'Tài liệu',
    'footer.support': 'Hỗ trợ',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.builtFor': 'Xây dựng cho nông nghiệp bền vững.',
    
    // About Page
    'about.title': 'Về AgriBeacon',
    'about.subtitle': 'Dẫn dắt tương lai nông nghiệp với công nghệ thông minh',
    'about.vision.title': 'Tầm nhìn của chúng tôi',
    'about.vision.text1': 'Trở thành nhà cung cấp hàng đầu thế giới về các giải pháp công nghệ nông nghiệp thông minh, toàn diện cho các trang trại cây lâu năm — giúp họ phát triển mạnh về kinh tế, sinh thái và xã hội.',
    'about.vision.text2': 'Chúng tôi hình dung một tương lai nông nghiệp kiên cường, dựa trên dữ liệu, ủng hộ tăng trưởng bền vững, trách nhiệm môi trường và tác động cộng đồng lâu dài — hoàn toàn phù hợp với các giá trị ESG toàn cầu.',
    'about.mission.title': 'Sứ mệnh của chúng tôi',
    'about.mission.text1': 'Chúng tôi trao quyền cho nông dân và doanh nghiệp nông nghiệp thông qua hệ sinh thái thống nhất của phần cứng và phần mềm — bao gồm máy bay không người lái tự động, robot, cảm biến IoT và phân tích AI — để tối ưu hóa mọi quyết định từ đất đến thu hoạch.',
    'about.mission.text2': 'Sứ mệnh của chúng tôi là chuyển đổi nông nghiệp thông qua độ chính xác, tự động hóa và thông tin chi tiết, mang lại tác động có thể đo lường được cho cả con người và hành tinh.',
    'about.name.title': 'Tại sao là "AgriBeacon"?',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': 'Nông nghiệp, nền tảng trọng tâm và trái tim của mọi việc chúng tôi làm.',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': 'Ngọn đèn dẫn đường hoặc tín hiệu thông minh chỉ đường phía trước.',
    'about.name.together': 'Cùng nhau, tên gọi phản ánh cam kết của chúng tôi trong việc cung cấp hướng đi rõ ràng, thông tin chi tiết thời gian thực và tự động hóa thông minh trong môi trường canh tác phức tạp và luôn thay đổi.',
    'about.values.title': 'Giá trị cốt lõi',
    'about.values.precision': 'Chính xác',
    'about.values.precision.desc': 'Chúng tôi tin vào các quyết định dựa trên dữ liệu và đo lường chính xác để đạt kết quả tối ưu.',
    'about.values.innovation': 'Đổi mới',
    'about.values.innovation.desc': 'Liên tục vượt qua ranh giới với công nghệ tiên tiến và cách tiếp cận mới mẻ.',
    'about.values.partnership': 'Đối tác',
    'about.values.partnership.desc': 'Làm việc sát cánh với nông dân để hiểu và giải quyết các thách thức thực tế.',
    'about.values.sustainability': 'Bền vững',
    'about.values.sustainability.desc': 'Xây dựng các giải pháp mang lại lợi ích cho cả trang trại và hành tinh cho các thế hệ tương lai.',
    'about.impact.title': 'Tác động của chúng tôi',
    'about.impact.farms': 'Trang trại hoạt động',
    'about.impact.acres': 'Diện tích giám sát',
    'about.impact.yield': 'Tăng năng suất trung bình',
    'about.impact.water': 'Tiết kiệm nước',
    
    // Careers Page
    'careers.title': 'Tuyển dụng AgriBeacon',
    'careers.subtitle': 'Xây dựng tương lai nông nghiệp',
    'careers.description': 'Tham gia sứ mệnh của chúng tôi để chuyển đổi nông nghiệp với công nghệ robot, AI và IoT tiên tiến. Tạo ra tác động thực sự đến an ninh lương thực và tính bền vững.',
    'careers.why.title': 'Tại sao chọn AgriBeacon?',
    'careers.why.subtitle': 'Chúng tôi không chỉ xây dựng công nghệ—chúng tôi giải quyết các vấn đề thực tế cho nông dân trên khắp Đông Nam Á.',
    'careers.benefits.impact': 'Tác động thực sự',
    'careers.benefits.impact.desc': 'Công việc của bạn trực tiếp giúp nông dân tăng năng suất, giảm lãng phí và xây dựng hoạt động bền vững.',
    'careers.benefits.tech': 'Công nghệ tiên tiến',
    'careers.benefits.tech.desc': 'Làm việc với máy bay không người lái tự động, robot, cảm biến IoT và AI/ML trong lĩnh vực thực tế đầy thách thức.',
    'careers.benefits.growth': 'Tăng trưởng & Cổ phần',
    'careers.benefits.growth.desc': 'Tham gia sớm, phát triển cùng chúng tôi và sở hữu một phần những gì chúng tôi đang xây dựng thông qua chương trình cổ phần.',
    'careers.positions.title': 'Vị trí tuyển dụng',
    'careers.positions.subtitle': 'Chúng tôi đang tìm kiếm những người tài năng muốn tạo ra sự khác biệt.',
    'careers.position.robotics.title': 'Kỹ sư Robot – Tự động hóa nông nghiệp',
    'careers.position.robotics.desc': 'Xây dựng robot và máy bay không người lái tự động đang chuyển đổi cách chúng ta trồng trọt. Tham gia cùng chúng tôi để làm cho nông nghiệp thông minh hơn, bền vững hơn và hiệu quả hơn.',
    'careers.position.location': 'Hà Nội',
    'careers.position.type.fulltime': 'Toàn thời gian',
    'careers.position.equity': 'Có cổ phần',
    'careers.position.onsite': 'Làm việc tại văn phòng',
    'careers.position.viewDetails': 'Xem chi tiết',
    'careers.noRole.title': 'Không tìm thấy vị trí phù hợp?',
    'careers.noRole.description': 'Chúng tôi luôn tìm kiếm những người tài năng. Nếu bạn đam mê công nghệ nông nghiệp và đổi mới, hãy liên hệ với chúng tôi.',
    'careers.noRole.contact': 'Liên hệ chúng tôi',
    
    // Contact Page
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Sẵn sàng chuyển đổi trang trại của bạn? Hãy thảo luận về cách AgriBeacon có thể giúp bạn phát triển thông minh hơn.',
    'contact.form.title': 'Yêu cầu demo',
    'contact.form.name': 'Họ và tên',
    'contact.form.name.placeholder': 'Nguyễn Văn A',
    'contact.form.email': 'Địa chỉ email',
    'contact.form.email.placeholder': 'nguyenvana@example.com',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.phone.placeholder': '+84 XXX XXX XXX',
    'contact.form.farmSize': 'Diện tích trang trại (hecta)',
    'contact.form.farmSize.placeholder': 'ví dụ: 200',
    'contact.form.message': 'Tin nhắn',
    'contact.form.message.placeholder': 'Hãy cho chúng tôi biết về hoạt động nông nghiệp của bạn và những gì bạn muốn đạt được...',
    'contact.form.submit': 'Gửi tin nhắn',
    'contact.form.success.title': 'Đã gửi tin nhắn!',
    'contact.form.success.description': 'Cảm ơn bạn đã quan tâm. Đội ngũ của chúng tôi sẽ liên hệ với bạn trong vòng 24 giờ.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Điện thoại',
    'contact.info.location': 'Địa chỉ',
    'contact.support.title': 'Giờ hỗ trợ',
    'contact.support.weekday': 'Thứ Hai - Thứ Sáu: 8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': 'Thứ Bảy: 9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': 'Chủ Nhật: Nghỉ',
    'contact.support.urgent': 'Đối với hỗ trợ kỹ thuật khẩn cấp, đường dây nóng 24/7 của chúng tôi có sẵn cho các đối tác Doanh nghiệp.',
    
    // Contact Sales Dialog
    'contactSales.title': 'Liên hệ bán hàng - Giải pháp B2B',
    'contactSales.description': 'Hãy cho chúng tôi biết về trang trại và nhu cầu kinh doanh của bạn, đội ngũ của chúng tôi sẽ liên hệ lại trong vòng 24 giờ.',
    'contactSales.companyName': 'Tên công ty/Trang trại',
    'contactSales.companyName.placeholder': 'Công ty Nông nghiệp ABC',
    'contactSales.contactName': 'Người liên hệ',
    'contactSales.contactName.placeholder': 'Nguyễn Văn A',
    'contactSales.email': 'Email doanh nghiệp',
    'contactSales.email.placeholder': 'nguyenvana@example.com',
    'contactSales.phone': 'Số điện thoại',
    'contactSales.phone.placeholder': '+84 XXX XXX XXX',
    'contactSales.farmSize': 'Tổng diện tích trang trại (hecta)',
    'contactSales.farmSize.placeholder': 'ví dụ: 500',
    'contactSales.location': 'Vị trí trang trại',
    'contactSales.location.placeholder': 'Tỉnh/Khu vực',
    'contactSales.cropTypes': 'Loại cây trồng chính',
    'contactSales.cropTypes.placeholder': 'ví dụ: Lúa, Cà phê, Rau củ',
    'contactSales.challenges': 'Thách thức hiện tại trong canh tác',
    'contactSales.challenges.placeholder': 'Bạn đang gặp những thách thức gì trong hoạt động canh tác của mình?',
    'contactSales.needs': 'Nhu cầu cụ thể & Giải pháp quan tâm',
    'contactSales.needs.placeholder': 'Hãy cho chúng tôi biết về các giải pháp bạn quan tâm (cảm biến IoT, máy bay không người lái, robot, nền tảng, v.v.)',
    'contactSales.submit': 'Gửi yêu cầu',
    'contactSales.success.title': 'Đang mở ứng dụng Email',
    'contactSales.success.description': 'Ứng dụng email của bạn sẽ mở với thông tin đã được điền sẵn.',
  },
  ja: {
    'home.hero.badge': '精密農業テクノロジー',
    'home.hero.title1': '精密な信号。',
    'home.hero.title2': 'スマートセンシング。',
    'home.hero.title3': '持続可能な成長。',
    'home.hero.subtitle': 'インテリジェントなエンドツーエンドの農業技術ソリューションで農場を変革。土壌から収穫まで、すべての決定を最適化。',
    'home.hero.explore': 'ソリューションを探索',
    'home.hero.demo': 'デモをリクエスト',
    
    'home.vision.title': '私たちのビジョン',
    'home.vision.subtitle': '多年生植物農場向けのインテリジェントでエンドツーエンドの農業技術ソリューションの世界有数のプロバイダーになること — 経済的、生態学的、社会的に繁栄できるようにします。',
    'home.mission.title': '私たちのミッション',
    'home.mission.text1': '自律ドローン、ロボティクス、IoTセンサー、AI搭載分析を含むハードウェアとソフトウェアの統合エコシステムを通じて、農家と農業ビジネスに力を与え、土壌から収穫までのすべての決定を最適化します。',
    'home.mission.text2': '私たちのミッションは、精密性、自動化、洞察を通じて農業を変革し、人々と地球の両方に測定可能なインパクトをもたらすことです。',
    'home.stats.farms': '最適化された農場',
    'home.stats.data': '日次データポイント',
    'home.stats.yield': '収量増加',
    'home.stats.water': '節水',
    
    'home.solutions.title': 'インテリジェントソリューション',
    'home.solutions.subtitle': '最先端の農業技術の完全なエコシステム',
    'home.solutions.autonomous': '自律ドローン',
    'home.solutions.autonomous.desc': 'インテリジェントな空中監視とデータ収集',
    'home.solutions.robotics': 'スマートロボティクス',
    'home.solutions.robotics.desc': '自動化された農業オペレーションと精密タスク',
    'home.solutions.iot': 'IoTセンサー',
    'home.solutions.iot.desc': 'リアルタイム環境監視とアラート',
    'home.solutions.ai': 'AI分析',
    'home.solutions.ai.desc': '最適な意思決定のためのデータ駆動型洞察',
    'home.solutions.viewAll': 'すべてのソリューションを見る',
    
    'home.cta.title': '農場を変革する準備はできていますか？',
    'home.cta.subtitle': '収量を増加し、廃棄物を削減し、持続可能な未来を築くためにAgriBeaconを使用している数百の先見性のある農場に参加してください。',
    'home.cta.demo': 'デモをスケジュール',
    'home.cta.learn': '詳細を見る',
    
    // Navigation
    'nav.technology': 'テクノロジー',
    'nav.resources': 'リソース',
    'nav.pricing': '料金',
    'nav.about': '会社概要',
    'nav.contact': 'お問い合わせ',
    'nav.login': 'ログイン',
    'nav.tryForFree': '無料で試す',
    'nav.contactSales': '営業に問い合わせ',
    
    // Technology menu
    'nav.technology.platform': 'プラットフォーム概要',
    'nav.technology.ai': 'AI分析',
    'nav.technology.connectivity': '接続性',
    'nav.technology.all': 'すべてのテクノロジー',
    
    // Resources menu
    'nav.resources.bestPractices': 'ベストプラクティス',
    
    // About menu
    'nav.about.aboutUs': '会社について',
    'nav.about.careers': '採用情報',
    'nav.about.contact': 'お問い合わせ',
    
    // Menu descriptions
    'nav.technology.platform.desc': '統合B2B農場管理',
    'nav.technology.ai.desc': 'ビジネス向け予測分析',
    'nav.technology.connectivity.desc': 'LoRaWAN & マルチネットワーク',
    'nav.technology.all.desc': '技術スタックを探索',
    'nav.resources.bestPractices.desc': '農業ガイド & ESG',
    'nav.about.aboutUs.desc': 'ミッション & ビジョン',
    'nav.about.careers.desc': 'チームに参加',
    'nav.about.contact.desc': 'お問い合わせ',
    'nav.pricing.desc': 'B2Bソリューション & パッケージ',
    
    // Footer
    'footer.company': '会社',
    'footer.solutions': 'ソリューション',
    'footer.technology': 'テクノロジー',
    'footer.resources': 'リソース',
    'footer.legal': '法的',
    'footer.copyright': '© 2024 AgriBeacon. 全著作権所有。',
    'footer.tagline': '精密な信号。スマートセンシング。持続可能な成長。インテリジェントな農業技術ソリューションで農家に力を与える。',
    'footer.quickLinks': 'クイックリンク',
    'footer.documentation': 'ドキュメント',
    'footer.support': 'サポート',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.builtFor': '持続可能な農業のために構築。',
    
    // About Page
    'about.title': 'AgriBeaconについて',
    'about.subtitle': 'インテリジェント技術で農業の未来を導く',
    'about.vision.title': '私たちのビジョン',
    'about.vision.text1': '多年生植物農場向けのインテリジェントでエンドツーエンドの農業技術ソリューションの世界有数のプロバイダーになること — 経済的、生態学的、社会的に繁栄できるようにします。',
    'about.vision.text2': '持続可能な成長、環境責任、長期的なコミュニティへの影響を支持する、回復力があり、データ駆動型の農業の未来を思い描いています — グローバルなESG価値観と完全に一致しています。',
    'about.mission.title': '私たちのミッション',
    'about.mission.text1': '自律ドローン、ロボティクス、IoTセンサー、AI搭載分析を含むハードウェアとソフトウェアの統合エコシステムを通じて、農家と農業ビジネスに力を与え、土壌から収穫までのすべての決定を最適化します。',
    'about.mission.text2': '私たちのミッションは、精密性、自動化、洞察を通じて農業を変革し、人々と地球の両方に測定可能なインパクトをもたらすことです。',
    'about.name.title': 'なぜ"AgriBeacon"？',
    'about.name.agri': 'Agri',
    'about.name.agri.desc': '農業、私たちの焦点の基盤であり、すべての活動の中心です。',
    'about.name.beacon': 'Beacon',
    'about.name.beacon.desc': '前進の道を示す導きの光またはインテリジェント信号。',
    'about.name.together': '一緒に、この名前は複雑で進化する農業環境において、明確な方向性、リアルタイムの洞察、スマートな自動化を提供するという私たちのコミットメントを反映しています。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.precision': '精密性',
    'about.values.precision.desc': '最適な結果を得るために、データ駆動型の意思決定と正確な測定を信じています。',
    'about.values.innovation': 'イノベーション',
    'about.values.innovation.desc': '最先端技術と新しいアプローチで常に限界を押し広げています。',
    'about.values.partnership': 'パートナーシップ',
    'about.values.partnership.desc': '農家と手を取り合って実際の課題を理解し解決します。',
    'about.values.sustainability': '持続可能性',
    'about.values.sustainability.desc': '農場と地球の両方に何世代にもわたって利益をもたらすソリューションを構築しています。',
    'about.impact.title': '私たちのインパクト',
    'about.impact.farms': 'アクティブ農場',
    'about.impact.acres': '監視エーカー',
    'about.impact.yield': '平均収量増加',
    'about.impact.water': '節水',
    
    // Careers Page
    'careers.title': 'AgriBeacon採用情報',
    'careers.subtitle': '農業の未来を築く',
    'careers.description': '最先端のロボティクス、AI、IoT技術で農業を変革するミッションに参加してください。食料安全保障と持続可能性に真の影響を与えます。',
    'careers.why.title': 'なぜAgriBeacon？',
    'careers.why.subtitle': '私たちは単に技術を構築しているのではなく、東南アジア全体の農家の実際の問題を解決しています。',
    'careers.benefits.impact': '真のインパクト',
    'careers.benefits.impact.desc': 'あなたの仕事は、農家が収量を増やし、廃棄物を削減し、持続可能な運営を構築するのを直接支援します。',
    'careers.benefits.tech': '最先端技術',
    'careers.benefits.tech.desc': '挑戦的な実世界のドメインで、自律ドローン、ロボティクス、IoTセンサー、AI/MLを扱います。',
    'careers.benefits.growth': '成長と株式',
    'careers.benefits.growth.desc': '早期に参加し、私たちと一緒に成長し、株式プログラムを通じて私たちが構築しているものの一部を所有します。',
    'careers.positions.title': '募集ポジション',
    'careers.positions.subtitle': '違いを生み出したい才能ある人々を探しています。',
    'careers.position.robotics.title': 'ロボティクスエンジニア – 農業自動化',
    'careers.position.robotics.desc': '食料の栽培方法を変革する自律ロボットとドローンを構築します。農業をよりスマートに、より持続可能に、より効率的にするために私たちに参加してください。',
    'careers.position.location': 'ハノイ',
    'careers.position.type.fulltime': 'フルタイム',
    'careers.position.equity': '株式利用可能',
    'careers.position.onsite': 'オンサイト',
    'careers.position.viewDetails': '詳細を見る',
    'careers.noRole.title': 'あなたの役割が見つかりませんか？',
    'careers.noRole.description': '私たちは常に才能ある人々を探しています。農業技術とイノベーションに情熱を持っている場合は、お問い合わせください。',
    'careers.noRole.contact': 'お問い合わせ',
    
    // Contact Page
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '農場を変革する準備はできていますか？AgriBeaconがよりスマートな成長をサポートする方法について話し合いましょう。',
    'contact.form.title': 'デモをリクエスト',
    'contact.form.name': '氏名',
    'contact.form.name.placeholder': '山田太郎',
    'contact.form.email': 'メールアドレス',
    'contact.form.email.placeholder': 'yamada@example.com',
    'contact.form.phone': '電話番号',
    'contact.form.phone.placeholder': '+81 XXX XXXX XXXX',
    'contact.form.farmSize': '農場面積（エーカー）',
    'contact.form.farmSize.placeholder': '例：200',
    'contact.form.message': 'メッセージ',
    'contact.form.message.placeholder': 'あなたの農業ビジネスと達成したいことについて教えてください...',
    'contact.form.submit': 'メッセージを送信',
    'contact.form.success.title': 'メッセージが送信されました！',
    'contact.form.success.description': 'お問い合わせいただきありがとうございます。当社のチームが24時間以内にご連絡いたします。',
    'contact.info.email': 'メール',
    'contact.info.phone': '電話',
    'contact.info.location': '所在地',
    'contact.support.title': 'サポート時間',
    'contact.support.weekday': '月曜日 - 金曜日：8:00 AM - 6:00 PM ICT',
    'contact.support.saturday': '土曜日：9:00 AM - 3:00 PM ICT',
    'contact.support.sunday': '日曜日：休業',
    'contact.support.urgent': '緊急技術サポートについては、エンタープライズパートナー向けに24時間365日対応のホットラインがご利用いただけます。',
    
    // Contact Sales Dialog
    'contactSales.title': '営業へのお問い合わせ - B2Bソリューション',
    'contactSales.description': '農場とビジネスニーズについてお聞かせください。当社のチームが24時間以内にご連絡いたします。',
    'contactSales.companyName': '会社名/農場名',
    'contactSales.companyName.placeholder': 'ABC農業株式会社',
    'contactSales.contactName': '担当者名',
    'contactSales.contactName.placeholder': '山田太郎',
    'contactSales.email': 'ビジネスメール',
    'contactSales.email.placeholder': 'yamada@example.com',
    'contactSales.phone': '電話番号',
    'contactSales.phone.placeholder': '+81 XXX XXXX XXXX',
    'contactSales.farmSize': '総農場面積（エーカー）',
    'contactSales.farmSize.placeholder': '例：500',
    'contactSales.location': '農場の所在地',
    'contactSales.location.placeholder': '都道府県/地域',
    'contactSales.cropTypes': '主な作物種類',
    'contactSales.cropTypes.placeholder': '例：米、コーヒー、野菜',
    'contactSales.challenges': '現在の農業の課題',
    'contactSales.challenges.placeholder': '農業運営で直面している課題は何ですか？',
    'contactSales.needs': '具体的なニーズと関心のあるソリューション',
    'contactSales.needs.placeholder': '関心のあるソリューションについてお聞かせください（IoTセンサー、ドローン、ロボティクス、プラットフォームなど）',
    'contactSales.submit': 'お問い合わせを送信',
    'contactSales.success.title': 'メールクライアントを開いています',
    'contactSales.success.description': '事前入力された情報でメールクライアントが開きます。',
  },
};

export const SimpleLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'vi', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <SimpleLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </SimpleLanguageContext.Provider>
  );
};

export const useSimpleLanguage = () => {
  const context = useContext(SimpleLanguageContext);
  if (context === undefined) {
    throw new Error('useSimpleLanguage must be used within a SimpleLanguageProvider');
  }
  return context;
};
